### ISSUE TITLE
Saendra Busts appearing incorrectly

### ISSUE THREAD

**Issue by mcgmcg** [Fenoxo/sourceTiTS#244]
The Shou bust for Saendra is appearing for all Saendra scenes, no matter how I manipulate bust preferences. (TiTS version 0.5.9)

**Comment by Gedan** [comment]
I think the report isn't actually a bug, but more the fact the only bust available for Saendra IS the Shou bust. None of the other bust options have anything, so if Shou is enabled at all, it's the one you're going to see.

Checked with all busts disabled, and it worked appropriately, as well as having each of the other bust options enabled; if Shoubusts are enabled, you'll see it. If Shoubusts are disabled, you won't.
