### ISSUE TITLE
Mimbrane + Lactation infinite boob growth

### ISSUE THREAD

**Issue by JoBiden** [Fenoxo/sourceTiTS#252]
On any characters I've made who have both breast mimbranes and lactate, boob-growth caused by mimbrane growth or boob-growth caused by lactation swelling will not fully disappear after the mimbrane reproduces or the swelling is relieved. In one extreme case, one such character who started out as a C cup, who I would reasonably expect to grow to maybe a HH cup if both effects were occurring at once, is currently a Y-cup. I thought it might have been fixed at the same time as a similar case with cock mimbranes in a recent patch, but Fenoxo claimed otherwise on the fenoxo blog.

**Comment by Gedan** [comment]
Should bcec24a

**Comment by Fenoxo** [comment]
Closin' dis as it's been a month with no additional grumps.
