### ISSUE TITLE
Various Typos etc

### ISSUE THREAD

**Issue by JoBiden** [Fenoxo/sourceTiTS#253]
The following 4 typos etc occur in conversation with Ambassador Juro:

"He points to a golden-planted myr female sitting at a desk"
planted should be plated

"At any rate, the both myr races have attracted the attention of Xenogen"
'the' should be removed

"the Fleet will avenge us on the few survivors of the native population"
I actually can't find anything strictly wrong with this sentence, but 'avenge us on' felt awkward to read

"it’s refreshing to see someone around here who understands that is through unity"
'is' should be 'it is'

"Her Mission"
Occurs in a button label for a conversation in which you talk to Nehzara about Steele's mission [female character in this case]. I believe it would be more accurate to say "Your Mission"

"You not have any kind of tauric body and have a penis"
'you not' should be 'you must not' - occurs in Nehzara's 'StorageCloset' tool tip if you don't meet prerequisites

"You’re most bad-ass looking babe here."
'You're most' should be 'you're the most' - occurs in conversation with Kara

"And you’re null... the heir of the late Victor Steele,"
null should be character name - occurs again in followup scenes

"When you can finally muster up the energy to move, you fiercely kiss her, your spent ERROR: NO WANGS DETECTED for simpleCockNoun() still buried within her."
Obvious error, occurs when Steele is female after "kiss her" when she is full female and confesses her love to you.

There are two paragraphs where steele puts on different strapons (same scene as above), I think only the double-ended one should be present, but personally I think it would be better if PC's could opt out of getting penetrated by a dildo if they're trying to be chaste for whatever reason. Along the same note, doing the "vaginal" scene as a female Steele with a hardlight immediately after resulted in a paragraph where a double ended strap on is attached, but referred to as 'it' - I think a paragraph introducing the strap on is missing. Additionally, in the cunnilingus scene, she pulls down your "null", which should in this case have been plain panties with a hardlight.  

small aside - Doing Embry 'appearance' when you first meet her is followed up with another scene as if you haven't already sat down and taken a menu.

**Comment by Gedan** [comment]
> "Her Mission"
> Occurs in a button label for a conversation in which you talk to Nehzara about Steele's mission [female character in this case]. I believe it would be more accurate to say "Your Mission"

This refers to Nehzara's mission, and not the players.

**Comment by Gedan** [comment]
> There are two paragraphs where steele puts on different strapons (same scene as above), I think only the double-ended one should be present, but personally I think it would be better if PC's could opt out of getting penetrated by a dildo if they're trying to be chaste for whatever reason. Along the same note, doing the "vaginal" scene as a female Steele with a hardlight immediately after resulted in a paragraph where a double ended strap on is attached, but referred to as 'it' - I think a paragraph introducing the strap on is missing. Additionally, in the cunnilingus scene, she pulls down your "null", which should in this case have been plain panties with a hardlight.

Please, continue to clarify these exact scenes. I didn't code them, and I don't know which functions they are; all I have to really go on is scene text such that I can Ctrl+F the codebase and find things.

**Comment by JoBiden** [comment]
"You take the strap-on from her, grabbing it by one of the black leather straps. The shaft is purple, with an extremely smooth surface, and a head slightly wider than the shaft. It’s the perfect shape for pegging her. Not only that, it’s double ended. A smaller but still sizable violet dildo faces inward, perfectly designed to be slid inside your slavering, terran pussy.

Belle reaches for her purse and pulls out what looks like parts of a strap on - she came prepared. Since you’re already wet, you slide it inside of your slick snatch. It feels so good going in, filling you up, and you sigh with pleasure. Your lover diligently does up the ties, secures your strap on, and makes sure it is properly in place."

Thats a direct dump of the two paragraphs in question

**Comment by JoBiden** [comment]
Also, I don't see any mention of Nehzara's mention in the "her mission" scene - the conversation seems to concern steele getting access to Kressia to search for the probe.

**Comment by Fenoxo** [comment]
Shit Fixt. 9f546093b0c05cd8edfe3a259da32e1b747cd3d0
