### ISSUE TITLE
Reaha body Mods can't change

### ISSUE THREAD

**Issue by blank-Observer** [Fenoxo/sourceTiTS#255]
well, after you bought reaha contract, she stated the terms that you can change her body mods later on. the problem is, how could i install it to her? even after i bought the mods, there isn't any menu to give it to her. it's the same with ausar treats. plenty scene of her suggest that anno request the treats but i can't give any to her. any thought for this problems ?

**Comment by JoBiden** [comment]
Just because a scene foreshadows that you can perform an action, doesn't mean its been implemented yet. Reaha is still a work in progress, Anno less so.

**Comment by Fenoxo** [comment]
Not yet in.
