### ISSUE TITLE
[0.5.14] Cunt Snake removable by Ausar Treats

### ISSUE THREAD

**Issue by Zsar** [Fenoxo/sourceTiTS#257]
I am fairly sure that this was reported before (by myself even) and supposedly fixed, but I cannot find the posted Issue anymore.

Anyway, reproduced with "bimbofied" half-Ausar, dogish Cunt Snake:

Appearance before, snake tail functional in scenes:
"A sinuous, almost snake-like tail waves behind you, covered in coat like the rest of you except at the tip."

Taking a couple of Ausar Treats:
"You feel something itching on your tail. Twisting around, you watch in a mix of horror and excitement as black bristles, the beginnings of a thick coat of fur, sprout up across the length of your reforming posterior appendage. It starts wagging as the change completes, leaving you with an ausar’s dog-like tail."

Sure enough, Appearance thereafter:
"A fuzzy black dogtail sprouts just above your compact posterior, wagging to and fro whenever you are happy."

Seeking out a Sydian male indeed shows the "Tailsuck" scene as disabled, tooltip stating that it "requires a tail vagina".

**Comment by Gedan** [comment]
Tentatively fixed in ae44b05 using tailTypeUnlocked.
