### ISSUE TITLE
[0.5.14] Burt's Zil artifact smuggling ring not affected by "Supply and Demand" perk

### ISSUE THREAD

**Issue by Zsar** [Fenoxo/sourceTiTS#259]
Considering that this is a Smuggler class perk and Burt... at least implies that he is smuggling... mayhap this should apply here?
Also the button to do so is labeled "Shop", which would indicate some kind of relation with "Buy" or "Sell".

Alas, currently, with and without perk, "Tasty-smelling Zil Ration" is worth 50 Credits.

**Comment by Fenoxo** [comment]
Burt's Zil stuff doesn't use the shop mechanics. Tough titties!
