### ISSUE TITLE
[0.5.14] Mimbranes are not setup to support multiple genitals

### ISSUE THREAD

**Issue by Zsar** [Fenoxo/sourceTiTS#260]
It seems that only the "first" vagina/penis can be settled by a Mimbrane, even though others would be valid by type.

Proper solutions would be to have one Mimbrane affect all of them or to allow for a Mimbrane on each individually.

**Comment by Seer5063** [comment]
Can verify, Mimbranes only attach to the first acquired of any genitals.

**Comment by Gedan** [comment]
All of the tracking setup presumes only a single genital too. I mean, I could modify it, but I'd probably be looking for the nearest window to jump out of long before I finish.

**Comment by Zsar** [comment]
Better now than later when more incompatibilities have arosen and the whole thing looks even more fubar, right?
... Looking at this code, some refactoring might be a good idea anyway. It will also fail to adapt to multi-foe combat (see line 3189 in mhenga.mimbranes.as).

Incidentally, these giant if-else-if structures look like prime candidates to go into an extra file. Additionally, if this language has anything like [this](http://www.cplusplus.com/reference/unordered_map/) or [that](http://docs.oracle.com/javase/7/docs/api/), a single such object could replace these blocks quite elegantly (reducing block size to ~1/3).

If something looks like a nightmare to maintain *now*, it probably requires a serious rework *as soon as possible*, before issues have a chance to pile up as the game gains new features (and, after all, we all want new features).
... This is where "Slaves to Armok" failed while "Slaves to Armok 2" prospers. If I am not mistaken, it is also a (the?) big issue of "Corruption of Champions".

**Comment by Zsar** [comment]
To follow up on my last comment, wherever such a structure exists:
```
var a:object;

if(a.equals(something))
  output A;
else if(a.equals(somethingElse))
  output B;
etc.
```
you might want to export the if-structure into a function
```
function output(a:object):bool
{
  if(a.equals(something))
    output A;
  else if(a.equals(somethingElse))
    ouput B;
  etc.
  else
    return false;
  return true;
}
```
and put that into a file named "<original file name>.output.as". Should increase readability of actual game mechanic code by a large margin.

I will hold up posting an example of replacing if-elses with unordered_maps (C++11 code, but looks very similar) and how that further eases maintainability, until you tell me that the possibility actually exists... if it does.

**Comment by Fenoxo** [comment]
Not happening. Way more work than its worth.

**Comment by Zsar** [comment]
So they will be deprecated and removed in a future version? Sad that, I kind of liked them.
