### ISSUE TITLE
[0.5.14]Busts disappear when coming back from Options menu

### ISSUE THREAD

**Issue by Seer5063** [Fenoxo/sourceTiTS#262]
When hitting "Back" from options menu, the previously displayed bust, and the location information disappear/change,

i.e. when a bust of Ogram & Anna is displayed, and when the listed location is "Planet: New Texas, System: Nye"(PC is in Customs Office on New Texas), clicking the Menu button,  the Options, then Back, will remove the bust and bust text, as well as the location, replacing it with "Welcome to TiTs" or sometimes "Cargo Thoroughfare", and in location, "An Erotic Flash Game, By Fenoxo", or sometimes Planet: New Texas, System: Nye"

I can reproduce it in any location where there is a bust  and location info displayed; during scenes, in battle, on ship, etc. It seems like it's a bug in the wrapper of the interactable UI, where the map and what not gets displayed

**Comment by Fenoxo** [comment]
Bug that's super tiny and a pain to fix. Not gonna mess with it.
