### ISSUE TITLE
[0.5.14] Hand So’s suddenly defeated in tarkus

### ISSUE THREAD

**Issue by blank-Observer** [Fenoxo/sourceTiTS#263]
well, this problem occurs after I create a new character in the game. when I explore the Tarkus room, I discover that Hand So already defeated. the scene was explained that I could access to some hidden room [didn't show in map] and change the gender production of the sex-bot or shut down it while gained the beads of hand so. The problem is, I didn't take the quest from Colenso and didn't have the GPS Triangulator device. is it overlapping in the event flags trigger or my saves were error?

**Comment by Fenoxo** [comment]
I THINK this was fixed a few builds back?

**Comment by blank-Observer** [comment]
Sorry for not reporting back. in latest public release [0.5.17] it already solved. thanks fen ^^
