### ISSUE TITLE
repeating & broken venus egg laying scene (pitcher plant)

### ISSUE THREAD

**Issue by CaptainPedantic** [Fenoxo/sourceTiTS#264]
my frustration with this is partly (if not mostly my fault), I was playing, got eggs laid in me by a pitcher lady, the another pitcher type creature attacked me, he/she (can't fully recall) then inseminated me after a while my character was giving birth, everything was fine, and then the text just started cycling similar paragraphs about how my character was in orgasmic bliss when being about to give birth. it didn't stop, what went wrong?

**Comment by Gedan** [comment]
Because Jacques put it so clearly:

Can you give the exact quote of the message that's spamming?

**Comment by CaptainPedantic** [comment]
no, sorry. I cannot, it was the scene where my character felt the egg coming, just before the scene where the venus egg comes out.

**Comment by Gedan** [comment]
Continuing on forum rather than hear, crossposting pointless etc.
