### ISSUE TITLE
Shekka typos and potential weapon damage type errors for the Arc Caster and Laser Carbine

### ISSUE THREAD

**Issue by Leo-Regulus** [Fenoxo/sourceTiTS#267]
In the Shekka 'Fuck Her' scene, there is a typo towards the end of the no knot variant that reads:

"...slipping halfway out of her. You take the moment to appreciate the shapeliness of her shoulder blades and the natural scent of her air."

The 'natural scent of her air' most likely should be 'natural scent of her hair' especially when compared to the knot variant of the scene.

Secondly, in the Round 2 variant of Shekka's Robot scenes, there is a typo when selecting the Mendova option:

"If you cant take it you should stop going easy on me with your choices,”

'If you cant take it' should be "If you can't take it".

Finally, the Laser Carbine and the Arc Caster may be using the incorrect damage types. The Arc Caster which sounds and seems to function as an electricity-based energy weapon is using Laser rather than Electric for its damage type, pulling GLOBAL.LASER rather than GLOBAL.ELECTRIC. Additionally, the Laser Carbine is using Thermal instead of Laser for its damage type when it sounds and appears to be a laser-based energy weapon, pulling GLOBAL.THERMAL rather than GLOBAL.LASER.

**Comment by Gedan** [comment]
Changed the weapon damage types around.

**Comment by Fenoxo** [comment]
Fixt typos via a2bd1549b0017b364d6e1a37e368a357cb300480
