### ISSUE TITLE
TiTS_0.5.1.6 Lane Gender confusion and First time meeting weirdness

### ISSUE THREAD

**Issue by BobTheLost** [Fenoxo/sourceTiTS#269]
I met Lane chose female Lane.
I ask for Hypnosis and this message appears:
"When she shuts the door behind you, it’s as dark as you remember it. The incense from the candles greets your nose, and already you feel yourself relaxing, your legs becoming languid as you walk. You turn to Lane, watching her remove his top, and then she walks past you, towards her seat"

"It's as dark as you remember it" is a weird thing to think since this it the first time doing this.
And at the end with the "watching her remove his top" is gender confused I guess.

**Comment by BobTheLost** [comment]
2nd time meeting Lane and choosing Aim.
"You thank him for her work again, and you leave her little hut, ready to tackle the day with the new and improved you."

**Comment by BobTheLost** [comment]
This time I chose Intelligence.
"Lane certainly seems positive about it. Do you ask her to improve your memory by, as he put it, ‘streamlining’ how your conscious mind recalls lessons and memories?"

**Comment by BobTheLost** [comment]
More gender confusion when lane becomes your mistress.
"You glance up from the codex, your finger hovering teasingly over the confirmation button, when you hand it back to her. He looks confused, before you tell her that you’d like to skip the foreplay. She smiles and stands from her chair; she crooks a claw at you, ordering you to follow, as she leads you behind the curtain and to the left, towards her bedroom.

By the time you enter behind your mistress, her shirt and pants have already been pulled offInvalid IF Statementif {Lane is female}, letting her heavy breasts bounce free in the wind – not that they were especially well concealed to begin with. She turns to you and, with a predatory grin, slides a claw across the fabric of her undergarment, tearing it away and revealing her wet, puffy cunt. Her genital slit is open and malleable, ready for you to play with; her labia waves at you, waiting for your pleasure."

**Comment by BobTheLost** [comment]
Again after you become enthralled by Lane.
"You thank him for his ‘generosity’ again."

**Comment by BobTheLost** [comment]
Another one.
"“You can no longer imagine life without Lane. Your days aren’t complete without worshiping her by giving him your body to mold.”"

**Comment by BobTheLost** [comment]
Got this message once I return to get hypnotized again:
"
Something bad happened! Please report this message:

TypeError: Error #1009
	at classes::TiTS/laneApplyService()
	at classes::TiTS/buttonClick()
"

**Comment by Gedan** [comment]
99% sure these are all handled.
