### ISSUE TITLE
More potential weapon issues: Gooey Pseudopod, Knife, and Warhammer

### ISSUE THREAD

**Issue by Leo-Regulus** [Fenoxo/sourceTiTS#271]
I've noticed a few more issues with weapons, their damage types, and their attack verbs; specifically, these are all for various melee weapons.

Firstly, Gooey Pseudopod is a 'slap', but uses GLOBAL.PIERCING rather than GLOBAL.KINETIC. It's a little odd that a slap from a limb made of goo would inflict piercing rather than kinetic damage to say the least. Additionally, the 'pseudopod' of Gooey Pseudopod is misspelled; it is spelled as 'psuedopod', but it should be 'pseudopod'. So it probably wouldn't hurt to fix that as well.

Secondly, Knife, which uses the attack verb 'slash' and reference slicing in its tooltip, causes piercing damage rather than slashing. So, this one can be corrected in one of two ways: either change the attack verb from 'slash' to 'stab' so the attack matches the damage, or change the damage type from GLOBAL.PIERCING to GLOBAL.SLASHING.

Finally, Warhammer uses the attack verb 'slash' while it utilizes kinetic damage. There are a couple of existing attack verbs which could be used to correct this: 'smack', which is used by the Raskvel Wrench as an example; or 'slam', as it is used by the Rocket Hammer.

**Comment by Gedan** [comment]
The first is a placeholder item. It's not actually intended to be used ever; it's simply "containing" some default stuff for Goo-like characters in case it comes up.

The other two I'll tweak now.
