### ISSUE TITLE
[0.5.14] Ausar Treats not producing human-shared body parts

### ISSUE THREAD

**Issue by Zsar** [Fenoxo/sourceTiTS#272]
Ausar Treats cannot be used to attain any body part ausars share with humans, if the character possesses a non-human version of said part.

Examples:
* Naleen face
* Naleen vagina
* Naleen genital slit

While a case could be made for not reverting "more-than-ausar" dog-morph-like parts, there is currently no way in-game to obtain those, so that point is moot.
(Also it would seem logical, that an item that may turn human into ausar, should symmetrically turn dog-morph into ausar.)

**Comment by Fenoxo** [comment]
Pretty sure this is working as intended.
