### ISSUE TITLE
Tits 0.5.17 Disarming Kara doesn't confine her to her beamsword, and some of Kara's stats don't show up.

### ISSUE THREAD

**Issue by Metaphallica** [Fenoxo/sourceTiTS#275]
You can use the Tech Specialist ability "Weapon Hack" to disarm Kara or disable her gun, and she gets the appropriate symbol, but then she keeps on using her gun on you.

Don't know if the same applies to Shade, but it's probably worth checking her.

I mean it's a little fishy to be able to "hack" somebody's handgun in the first place, and I don't see it as being remotely plausible, but that doesn't mean the ability should literally "not do what it says" after costing energy.

--

In an unrelated note, the stats "Level", "Race" and "Sex" all just show up as 0 in Kara's stat bar, and so I assume it's worth checking Shade's too.

**Comment by Gedan** [comment]
Fixed the latter part of this today.

**Comment by Fenoxo** [comment]
Fixt the former.

**Comment by Fenoxo** [comment]
3abeb0b8c0e6af59db080035f0ef58fbd27fe7e1
