### ISSUE TITLE
Issue after repeated interactions with Lane

### ISSUE THREAD

**Issue by HikaruTenshi** [Fenoxo/sourceTiTS#277]
Upon having been hypnotized by Lane several times (after reaching the point that once a day he subtracts 500 credits per day) this issue comes up which, although I did not see any other effects, for me reduced my current credits to 0 even though at the time I had over 4000.

TypeError: Error #1010
	at classes::TiTS/statusTick()
	at classes::TiTS/processTime()
	at classes::TiTS/rest()
	at classes::TiTS/buttonClick()

**Comment by Gedan** [comment]
I think I already fixed this earlier today. Pretty sure I did at least.
