### ISSUE TITLE
Sudden stat decrease 

### ISSUE THREAD

**Issue by The-Maverick** [Fenoxo/sourceTiTS#278]
Suddenly while I was roaming Tarkus I noticed my stats had changed. My strength had changed from 5 to 1 and my reflexes 20 to 16

**Comment by Fenoxo** [comment]
Can't do much with this. There's not enough information to find anything. If you can work out a way to reproduce it, I can fix it.

**Comment by Gedan** [comment]
Trip?

I actually think I recently fixed this. I was improperly creating a status effect in part of Anno quest and it was leaving the Trip effect. I ALSO think I wrote some stuff to clean it up as well...
