### ISSUE TITLE
[0.5.17] Third breast not intuitively reachable

### ISSUE THREAD

**Issue by reticent-anon** [Fenoxo/sourceTiTS#284]
It looks like the logic to receive the third breast from medical experimentation is only reachable if you have been immobilized by your gonads.  And even then there's a 50% chance you'll receive a third nut rather than a breast when you get dragged in for remobilization.

Third breast occurs in the bigBallBadEnd event.
The bigBallBadEnd event only gets queued by the function nutSwellUpdates.
The function nutSwellUpdates is conditioned on having some number of balls.

I'd assume the third breast should be attainable without having to give yourself balls.

**Comment by Fenoxo** [comment]
I'm sure someday we'll have another way to get at it. For now, it's the only way. It's kind of an easter egg.
