### ISSUE TITLE
A couple issues that may or may not be bugs

### ISSUE THREAD

**Issue by SeanaRose** [Fenoxo/sourceTiTS#285]
As the heading says, I have found a couple issues that may or may not be bugs.

The first is with the Terran Treats having no effect on the cock slit from the Naleen Nips.  It says it returns to normal, but the slit is still there in the character description, and if you use another Terran Treat, it again says the slit is removed, but nothing actually happens..

The second issue is with the use of condensol and the horse-cock item you can find.  If you are male, and use the condensol to completely remove your cock, then, while still under the influence of the condensol attach the horse-cock item, when the condensol finally wears off, you will end up with either a 48" horsecock or a 64" one depending on if you had to use 3 or 4 condensol to remove your original cock.

Again, I'm not sure if these are bugs, or are meant to happen, but they both seemed off to me.

**Comment by Fenoxo** [comment]
Fixed the former via c9d49ce2fe3e508fc05031cfdf3e45a123097eb7
Please place separate bugs in separate issues.

**Comment by Fenoxo** [comment]
Latter fixt via bc7a1a4190b94076b91e234162609c51e85f225d
