### ISSUE TITLE
[0.5.17] Something bad when giving into super-lactation

### ISSUE THREAD

**Issue by reticent-anon** [Fenoxo/sourceTiTS#286]
>You feel a strong urge to relieve the unbearable pressure your lactating mammaries are experiencing; but thanks to the enhancements to your prodigious melons, you are confident they won’t ever stop - or even slow down - milk production, and you find it easy to resist.
>
>Something bad happened! Please report this message:
>
>null

To reproduce:

1. create a female character with the milky perk
2. visit new texas and take the treatment (treated milk)
3. build up lust to enable the masturbate button
4. take a milkmaid's aid to ensure you're heavily producing
5. select masturbate and then milk

**Comment by Fenoxo** [comment]
Was able to reproduce the first part but not the bug itself. Could I have a copy of your save to fiddle with? You can upload it as a forum attachment on http://forum.fenoxo.com/

**Comment by reticent-anon** [comment]
corresponding thread on the forum: http://forum.fenoxo.com/thread-12377.html

The message was a little different this time.  Difference could the operating system.  Original non-descript 'null' was while running linux.  This time it was on a windows desktop.

>ArgumentError: Error #1063
>	at classes::TiTS/buttonClick()

**Comment by Gedan** [comment]
I believe I've already fixed this for 0.5.18+.

**Comment by kingpingpong** [comment]
In response to reticent-anon, I've only been playing on a computer running Linux, only ever seen "null" appear, never something more detailed. Don't know if this error reporting is an OS issue or can be fixed/worked around in the code

**Comment by Gedan** [comment]
It would not surprise me to discover that exception handling in non-windows versions of flash-players don't work. Shit, it barely works on Windows as-is.

**Comment by kingpingpong** [comment]
Figured it was because of the whole flash-doesn't-actively-support-linux-if-it-doesn't-have-to. Any idea if that could be fixed some time down the road (probably minor issue which will only get looked at when you're bored, decide to working on game, and don't see too much to do. I assume.)

**Comment by Gedan** [comment]
Nothing on our end; the exception handling is fucked in the player itself. It's dumb as shit, and I've done whatever I can to get literally ANYTHING useful out of it at all already.

**Comment by kingpingpong** [comment]
Well at least you gave it the ol' college try

**Comment by reticent-anon** [comment]
I can confirm that the scene works in version 0.5.22.  Thanks for being aware and taking care of it before this was even posted!
