### ISSUE TITLE
Mispells in Shekka's scene

### ISSUE THREAD

**Issue by Frahuenheld** [Fenoxo/sourceTiTS#287]
¤Shekka (Fuck Her) - Mispelling
You pull away from the fidgeting mechanic. Her hands are shaking as she swaps components, and her breath is as ragged as and (should be 'an') endurance runner’s. She’s still managing to do her work, though. The jumpsuit gives way around her hips, stretching before rolling down her scaly hips. It clings to her sopping-wet slit in liquid-assisted defiance before finally breaking away, carrying a glossy sheen as a moment of its time wedged into her crotch. You grunt in appreciation of the fine ass you’ve revealed while you push her clothing to the ground.
...
Shekka’s legs slam against the table as you take her from behind, pressing on her hard enough that she winds up pressing her tits around her project and sending her tools scattering away. Her lips cling to your piston like oiled cylinder walls, and as you really start to give it to her they only seal tighter around you. Every forceful thrust is accompanied by lurid squelches, every cock-hilting thrust matched by affectionate, muscular squeezes from Shekka’s box. The impacts cause you to bump her rearward clit repeatedly, and she moans each time. These raskvel (I think it should be 'raskvels') were made to be fucked from any angle; no matter how you take them, one of their clits will be happily sparking.

**Comment by Fenoxo** [comment]
Latter is correct. See the codex entry. Former fixt via: bb7bec30d7e21c1cc2a28d3f6fd9b04dd848e449
