### ISSUE TITLE
Treatment Breast Growth Messages Show Different Size than Appearance

### ISSUE THREAD

**Issue by stevensilver** [Fenoxo/sourceTiTS#288]
Appearance breast sizes advance from HHH -> I
The Treatment messages assume breast sizes advance from HHH -> big HHH -> I.

As a result, the two are out of line after breast rating is 23 or greater. It starts when breast rating goes from 23 to 24 (//HHH -> big HHH).

Also, there are one to many Treatment breast growth messages for the current setup. They range from breastRatingRaw < .5 to breastRatingRaw < 31. But, breast growth only happens when breastRating() < pc.statusEffectv1("Treated").
pc.statusEffectv1("Treated") has a maximum value of 30, as assigned in Items/Miscellaneous/Treament.as. Note that 9 + rand(22) ranges from 9 to 30.

This setup never lets that (imo: awesome) big J -> JJ message display. I'm not sure which part you're going to change, but please make sure Sinarra still gets max boobs when you're done.

And finally,
I love your work, thank you very much.

**Comment by Fenoxo** [comment]
Fixt via 41987377915d906400d9a8b8a1fd74392bc2047b
