### ISSUE TITLE
Nuki Nuts perk seems to be completely broken

### ISSUE THREAD

**Issue by MillaSteele** [Fenoxo/sourceTiTS#289]
balls never get any bigger as ive had Vanae squirt their milk on my character to increase production and they never get any bigger. doesnt work on new or old characters. also tweeked the ball fullness in Minerva to quite a impossible number for the game and it never goes beyond just being on the first part of the perk of just being full

**Comment by MillaSteele** [comment]
also seems that if your a full Kui-tan female or just dont have the perk Nuki Nuts it acts like you do

**Comment by Fenoxo** [comment]
Fixt already.
