### ISSUE TITLE
Error Looting Tam-wolf, told to report it

### ISSUE THREAD

**Issue by kingpingpong** [Fenoxo/sourceTiTS#290]
Well, you’re not a drone expert, but... how hard could it be? You pull a cord from your codex to an exposed datajack on the back of Tam-wolf’s canid cranium, and quickly find your screen flooded with seemingly random messages and diagnostics.

Shit. You can’t make heads or tails of this! With a frustrated grunt, you yank the cord out of the useless canine drone and step back from the bench.

There was an error looting an the item that was looted didn’t actually exist.

Something bad happened! Please report this message:

null

**Comment by kingpingpong** [comment]
And taking it again, in the exact same way, didn't repeat the issue. Hmm...

**Comment by Fenoxo** [comment]
Fixt via 6fd4fe268408740d8690b7e8e966b3edca3129cc
