### ISSUE TITLE
Nobody expected this

### ISSUE THREAD

**Issue by Frahuenheld** [Fenoxo/sourceTiTS#291]
![2014-11-02-10-36-39](https://cloud.githubusercontent.com/assets/9006443/6035660/1cb1e6ca-ac16-11e4-8d49-7ff9b8337480.jpg)

I think nobody really expected for someone to reject her xD

P.S: The pic is old but I tried in the most recent free version and happened anyway.
P.S2: At least this happens on the Android version. I don't know if it happens on the pc version.

**Comment by Fenoxo** [comment]
Fixt via f06adeb05396c83bcd4ae1c9db1c8a4ebef84757
