### ISSUE TITLE
leg feet description and nuki trans

### ISSUE THREAD

**Issue by MillaSteele** [Fenoxo/sourceTiTS#292]
Seems the leg description is off. "Zero normal human legs extend below your waist, ending in normal human feet." and there's no Nuki feet/leg transformation has popped up and i used like a crap ton of cookie's to see if it showed up but it didnt

**Comment by Fenoxo** [comment]
...well, that is a fun pair of bugs. I'll look into it.

**Comment by Fenoxo** [comment]
The root cause might be that the legCount variable is set to 0. Not sure if it's a save editing accident or a bug in previous versions of the game. I couldn't find anything that would set it to 0 nowadays.

**Comment by MillaSteele** [comment]
well its not save editing cuz my chrome freaked out on teh update and it doesnt see any of my saves

**Comment by Fenoxo** [comment]
I'm pretty sure I resolved this one a while back.
