### ISSUE TITLE
Jack/Jill

### ISSUE THREAD

**Issue by MillaSteele** [Fenoxo/sourceTiTS#293]
seems something screwed with the game knowing whut you choose for your cuzin as im getting into the fight with Dane and it doesnt know which one i choose.
"Jack/Jill sneers and steps aside, saying, “Some people call ausar humanity’s lapdogs. Dane’s more of a guard dog."

**Comment by Fenoxo** [comment]
Ugh. This isn't the first time we've had this reported, but we haven't had any luck tracking it down. So far as I can guess, somewhere the data isn't getting stored or loaded properly and is getting reverted to the default.

**Comment by MillaSteele** [comment]
well this is the first time ive encountered it since the time you fixed it the first time.youll get it situated for good somehow
i belive

**Comment by Gedan** [comment]
See #296
