### ISSUE TITLE
[0.5.17] Bug with Membrane feeding

### ISSUE THREAD

**Issue by Omegano** [Fenoxo/sourceTiTS#297]
TypeError: Error #1010
	at classes::TiTS/feedAMimbrane()
	at classes::TiTS/mimbraneFeed()
	at classes::Creature/orgasm()
	at classes::TiTS/fuckAnnoWithScienceYoFukkinLadyBoi()
	at classes::TiTS/buttonClick()

I had a Mimbrane on my cock, then used condensol to get rid of it.  Went to have some fun with Anno, and this error appeared.  Probably something to do with the game having no idea how to handle a Mimbrane on a body part that no longer exists...

**Comment by Gedan** [comment]
Ye, exactly the reason. I figured one of the items was doing this, I just had no idea which and now I know. Good work :+1:
