### ISSUE TITLE
so i did a little test

### ISSUE THREAD

**Issue by MillaSteele** [Fenoxo/sourceTiTS#299]
Turns out its the Nuki Cookie's that give the Zero legs thing. i guess something went wrong when they try to give you Kui-legs as it never shows up in the TF. i started a new character and made her a Kui-Tan. Before she had 2 legs and after she had zero

**Comment by Fenoxo** [comment]
Gonna go with no on this. Nuki-cookies doesn't set legCount anywhere. Most likely you had a leg type that doesn't have dynamic leg counts set up, so it appeared as 2 even though the legCount variable is fucked.
