### ISSUE TITLE
Irellia and Myrellion errors

### ISSUE THREAD

**Issue by Alkahest** [Fenoxo/sourceTiTS#301]
Standing erect like can be difficult for a queen.

My vas will have missed my guidance.

You can imagine the regent doesn’t allow many sample their delights

“Noone has ever asked me that before.

You suggest that perhaps she shouldn’t dismiss all the drones, also asking her if she hashave a favorite male servant.

You like my pussy, null Steele?

MALE CHARACTER:
"With a final, glorious thrust, he presses his prodigious length deep inside of you until his tip is kissing your womb. "

SELECT YES FOR MONEY OPPORTUNITY
"
You thank the small creature for its time but decide to go on your way. It waves disappointedly but still energetically from its podium as you leave.

Let’s make a deal:

You decide to inquire further about this money-making opportunity.
"

**Comment by Fenoxo** [comment]
"My vas will have missed my guidance"
Not a typo.

**Comment by Alkahest** [comment]
My mistake then I prolly missed what vas was.

**Comment by Fenoxo** [comment]
Fixt via 3d7bd95097f9b2b81b22de5b20c1a5e7938c1f75
