### ISSUE TITLE
Embry Anal

### ISSUE THREAD

**Issue by ayyar135** [Fenoxo/sourceTiTS#302]
I waited until after embry had a vagina to do the pitch anal scene for the first time, so i had already had vaginal intercourse with her several times.  Despite this, when i tried anal with her the first time she still gives the lines about

“Um, you know, we’ve... n-never really had sex, you know? Not like, for real. I’m always pleasuring you, or you’re pleasuring me, but we’ve never really done it, you know-?” Belle boldly states, though her eyes are looking down at her feet. “... I-I was thinking, maybe, you want to use my ass—?”

Which is a bit jarring when you have already been intimate with her.  Not a big bug but it definitely caught my attention.

**Comment by Fenoxo** [comment]
Fixt c20e0415a0618fe0c3d4a28254ecad6baf816a79
