### ISSUE TITLE
[0.5.22] Vanae tail missing in appearance screen and Lightning Duster tool-tip issue

### ISSUE THREAD

**Issue by Leo-Regulus** [Fenoxo/sourceTiTS#303]
Firstly, the Vanae tail transformation does activate when Sky Sap is used and the PC's tailType is set to the correct value when this occurs. However, no change occurs in the Appearance screen if tailless, or the description goes from describing a tail to not mentioning any tail in the case of a PC that already had a tail. Of course, this could just be that a description has not been written up yet for PC's with a Vanae tail, in which case this section can just be ignored or kept as a note that it is still missing.

[Deleted false bug report. Sorry about that.]

**Comment by Gedan** [comment]
Have you actually tested the lightning duster? Because  you should probably actually test the lighting duster before insinuating that it's broken.

**Comment by Leo-Regulus** [comment]
Sorry, that was my fault, made a foolish assumption when I noticed the flipped tool-tip. The Lightning Duster does still reduce damage from Electrical attacks. I apologize. 

However, now that does bring up a real issue, its tool-tip displays a -100% to the resistance rather than a 100% like every other item that raises resistance. Anyways, sorry for that incorrect report in my earlier haste.

**Comment by Fenoxo** [comment]
Bumfin' fer viserbilities
