### ISSUE TITLE
[0.5.22] Flahne Legacy Content: Certain sections don't take PC's cumType into account

### ISSUE THREAD

**Issue by Leo-Regulus** [Fenoxo/sourceTiTS#304]
While this isn't a big deal, certain sections of Flahne's content don't take the PC's cumType into account and default to white. So, nothing major or game-breaking, just a little odd when she turns or interacts with 'white' rather than a color appropriate for alternate cum types. Anyways, here's what I've noticed so far:
______________________

The following three are for the scene "Bend Her Over":

"until your seed begins to press against her skin, coloring her white and swelling her form"

"swollen, near-white"

"With a wink, Flahne reaches out an enormous, off-white arm, unlocking the door nearest to you."
______________________

______________________

This last one is for the scene "Get Stuffed":

"your cock, still buried between Flahne's tits, twitches and spurts, staining her cleavage white with your sticky seed"
______________________

These are all of the sections of Flahne's scenes that do not take advantage of the pc.cumColor, pc.cum, etc. and can result in mismatched scenes.

**Comment by Fenoxo** [comment]
Danke! Fixed via d1c3fb1d8ef959d852c315c57714b25834a52458

**Comment by Fenoxo** [comment]
Fixt via d1c3fb1d8ef959d852c315c57714b25834a52458
