### ISSUE TITLE
[0.5.22] Electrical damage resistances acting as vulnerabilities possible issue

### ISSUE THREAD

**Issue by Leo-Regulus** [Fenoxo/sourceTiTS#305]
After my previous erroneous bug report on the Lightning Duster, I noticed a few other oddities in regards to Electrical damage and resistance. Electrical damage was actually received/increased while wearing the Lightning Duster with the Steeletech Suit, Smart Clothes, or TST Armor. So, I performed a number of tests for verification this time as I had the time to do so and here are my results:

Control against Shade, No Gear: Lowest damage I noticed being received from her Arc Caster attack I used as the baseline was 24 while the highest I observed was 34

Steeletech Suit Test: Minimum damage observed was 33 and maximum seen was 43

Smart Clothes Test: Lowest damage I recorded being dealt was 32 and the highest viewed was 44

TST Armor Test: Minimum damage received was 29 while the maximum observed was 41

So in short, the TST Armor increases Electrical damage received by 20% rather than decreasing it by this amount while the Smart Clothes and Steeletech Suit are even worse since they increase the damage by 30%. This is at odds with the tool-tips of at least the TST Armor and Smart Clothes as they are described as being energy resistant and great insulators respectively.

Additionally, I tested Shade's Shield since it is supposed to be vulnerable to electrical attacks, and the results of that test verify that it is vulnerable. Damage range dealt to Shade with a Laser Carbine was 29 to 35 while the damage inflicted by the equally powerful Electrogun spanned 35 to 41 in my tests with the Electrogun's damage dropping to 1 once her shield was depleted. I also edited a copy of Shade's shield into the PC's inventory as a final test, and it received damage of a similar magnitude as the TST Armor plating, verifying a 20% vulnerability. So while the shield's vulnerability to Electrical damage checks out, the resistances of the TST Armor, Steeletech Suit, and Smart Clothes to Electrical damage are actually vulnerabilities.

**Comment by Fenoxo** [comment]
Fixt via f72dac5906e92179165fc2b105e11a734c61c64d
