### ISSUE TITLE
SkySap not adding squirt/double to new bits

### ISSUE THREAD

**Issue by Chase-san** [Fenoxo/sourceTiTS#306]
SkySap does not give you double clit and squirter when creating a new vagina, despite claiming to do so.

**Comment by owen450** [comment]
it does give you double clit, try taking some more, however i'm fairly certain it does not give you squirter

**Comment by flamefight** [comment]
It does give squirter, had it happen lots of times as I was using it in transformations.

**Comment by Fenoxo** [comment]
Fixt via 58537886ac5d7215db836e023688ba625c94cc1c
