### ISSUE TITLE
[0.5.22] Terran Treats don't remove Tenta hair

### ISSUE THREAD

**Issue by BobTheLost** [Fenoxo/sourceTiTS#308]
After using sky sap to get tentacle hair I used Terran Treats to get rid of it but no matter how much I use the Tenta hair stays. I even put on debug mode to spam Terran Treats.

**Comment by flamefight** [comment]
I also feel that this is something that the Terran Treats should get rid of, as well as the Ausar treats and  several other of the core race transformatives when they come out, but right now neither of those have that functionality. However if you want to be rid of tenta-hair right now, 'nuki cookies do have a chance to change non-standard hair types into normal brown hair.

**Comment by Fenoxo** [comment]
Fixt here: http://forum.fenoxo.com/thread-12516.html
