### ISSUE TITLE
[5.22 Android] Rival creature has been previously configured 

### ISSUE THREAD

**Issue by StickyJimmy** [Fenoxo/sourceTiTS#309]
Here's what happened,  I start my save game I am at the nurse office, I get a message saying there's been a error with what rival gender I chosen, I select the one I chosen before.  I then travel to myrellion then I talk to lyralla get the pass to enter the city. I then go into the city then talk to the queen and accept the mission but when I move a few blocks I get this message:

ERROR: Rival creature has been previously configured, but has reverted to defaults. Debug data:(ButtonName:Next) (Func: mainGameMenu) 

Something bad happened!

Please report this message, and include any prior scene text or a description of what you did before seeing this message:

Version: 0.5.22

Error: ERROR: Rival creature has been previously configured, but has reverted to defaults. Debug data:(ButtonName:Next) (Func: mainGameMenu) 
	at classes::TiTS/jackJillDetector()
	at classes::TiTS/buttonClick()

**Comment by Gedan** [comment]
Sounds like the root issue is something Android related; the only people that have been reporting the message are all people playing on an Android device afaik.

I'm going to have to test this in-emulator and figure out what the shit is going on, urgh.

What device are you playing on? 
What version of Android is it running?

**Comment by Gedan** [comment]
What device are you playing on? What version of Android? etc.

**Comment by StickyJimmy** [comment]
Oh sorry for late reply, I'm on a Galaxy s5 with  kit-kat

**Comment by Gedan** [comment]
I think we've got the true cause of this handled now.
