### ISSUE TITLE
Save data verification failed

### ISSUE THREAD

**Issue by Ultraking** [Fenoxo/sourceTiTS#310]
I have a save that is 60 days in, whenever I try to save the game it gives me this error: Save data verification failed. Please send the files ‘broken_save.sol' and ‘TiTs_2.sol' to Fenoxo or file a bug report!
Rival has been serialized with default properties.

I tried loading older save files that I have on my computer from 53 days to 58 days, they give me the same error, I tried to make a new character and I was able to save.

This is the screen telling me the error.

![65ab0ce502ca105ef5a980ac5b046cc9](https://cloud.githubusercontent.com/assets/11149418/6319845/44aafcec-ba9a-11e4-80d9-51cd0bf8f7d5.png)

**Comment by Gedan** [comment]
Try to move between rooms after loading a save, and you should (maybe?) get a prompt asking you to 'fix' your Rivals gender.

Try saving after that.

**Comment by Ultraking** [comment]
It gave me the same error but with an added line. 
Lane has been serialized with default properties.

(https://cloud.githubusercontent.com/assets/11149418/6320818/badd0a1a-bab6-11e4-90b6-813f9b6399f3.png)

**Comment by Ultraking** [comment]
Ah, I also decided to do some investigating now that I remembered who Lane was. When I revisited lane I found that Lane's gender had been swapped and that Lane is now being treated as a guy.

**Comment by Gedan** [comment]
It's not been swapped, it's been reverted to a default state which is the problem.

ps do you happen to be playing on an Android device?

**Comment by Ultraking** [comment]
Nope, I'm on a laptop running windows 7.

**Comment by Gedan** [comment]
Can you upload one of your saves that triggers this please? Wanna look into this asap.

**Comment by Ultraking** [comment]
Alright, I found where chrome and firefox saves games on my computer, and I put the day 58 and the day 53 saves into this mega download. https://mega.co.nz/#F!BcpyhDiC!wjAfFMOSaY3uJHctZgzTWA

**Comment by Gedan** [comment]
What version of Flash Player are you using?

**Comment by Ultraking** [comment]
16.0.0.305

**Comment by Ultraking** [comment]
Thanks for looking into this and implementing this fix .
