### ISSUE TITLE
Anno's bug [0.5.22]

### ISSUE THREAD

**Issue by Frahuenheld** [Fenoxo/sourceTiTS#313]
After finishing the mision about the gray goo (I choose to stop them) I rejected Anno's offer to join her in the bath and this is next thing I see:

You’re still in combat, you ninny!The inside of the Steele Tech outpost is a cluttered mess of rusty alien technology stacked ten feet high. Pillars of engine parts and disassembled devices you can’t identify reach to the ceiling, making the shop seem more like a storage room than a storefront. Anno is sitting behind the counter, working on some paperwork. She smiles slightly at you. “Hey, boss. What’s up?”

So I went outside this place and everywhere I go there is the description of the location followed by this sentence: You’re still in combat, you ninny!
Another thing I noted is that Anno's ability (the one that improves your accuracy) was still in my status bar.

All went back to normal after I got into a fight.
Note: I wasn't using Debug or Silly mode and didn't edited my character.

**Comment by Fenoxo** [comment]
Fixt via a27f339dc8d2e731954fff83eb0f2a0b065e802b
