### ISSUE TITLE
Mispells so far [0.5.22]

### ISSUE THREAD

**Issue by Frahuenheld** [Fenoxo/sourceTiTS#315]
¤Jill in Mhe'ga (Insulting) - Double 'form'
Jill sneers and steps aside, saying, “Some people call ausar humanity’s lapdogs. Dane’s more of a guard dog.” The form form of a hulking brute emerges from behind her, in the shadows.

¤Gianna (Talk > ExOwner) - Missing word
“Decent. A little forgetful at times.” The android’s eyes flicker as (she) thinks. “He wasn’t even very sexually demanding. I could entice him into getting his rocks off twice a day, but if I wasn’t trying to turn him on, he probably never would have asked me.” Her eyes twinkle fondly. “After, he’d snuggle up with me a while until he fell asleep. Or, if we did it in the morning, sometimes he’d toss me a controller and make me play one of his favorite games with him. Other times, I’d get to be a test audience for a speech.”

¤Gianna (Talk > Big T) - Mistakes
“Not really. Sure, the impact damaged some of my internals and knocked me flat, but it isn’t like he didn’t have a high-dollar hovertruck. You know, the kind the kind (right here is one) with distributed force projectors strong enough to let it fly a few hundred feet in the air.” She gestures with her hands to create a fair approximation of a flying truck - or brick. One of the two. “Anyway, I got pushed a few inches into the mud and left with a half-dozen system shorts and synthskin breaches.”
...
Spreading her arms, the pale-skinned android looks radiant. “And now here I am. I have a ship to live in, a job that pays me a few credits, and something of a family. Truth be told, I don’t think he knows how to treat me. I may look like a girl, but I don’t smell like one. And here, that’s almost as important.” She shrugs. “So I get to be something between and (this 'and' shouldn't be here) a son and daughter, I suppose.”

¤Gianna (Sex > Vaginal) - Mistake
Blinking dreamily, she leans over you and begins to grind her pelvis against your own, twisting and twirling to an unseen, thumping beat, her soaked pussy squelching audibly. You can feel the inside of her passage rhythmically caressing you. Through artful design, Gianna’s human vagina is more nimble than a flutist’s fingers and nearly as wet as a galotian quim. Concentric ripples flutter over your shaft. Long strokes of slow pressure slide along the underside of your length from stem to stern, and your head (this 'head' shouldn't be here) cock-head is routinely suckled as if it was inside the most talented slut’s mouth.

¤Ellie (Talk > Pheromones) - Mispell
You find yourself unconsciously shifting a little closer to Ellie, breathing in deep through your nose to drink deep of that heady, potent admixture of pheromones that seem to be all but pouring off of her. You manage to ask her about them, though you’ve barely gotten a word out before you notice you’re (should be 'your') mouth is watering... and that you have a serious hankering to eat a little ‘taur pussy.

¤Big T (Talk > New Texas) - Possible mispell
Tee guffaws and slaps his knee. “That not enough for you, Steele? What else can ya want from a home, huh? Sure, it ain’t the most exciting place in the galaxy. Just ask Ogram down at Customs. He’s always complaining about now (maybe 'not') having pirates and kidnappers to shoot. Or at least he does when that Amma of his isn’t keeping him busy. Ha! That’s the real beauty of our little world, isn’t it? There’s always something to distract you from your woes. Never a bad day on New Texas - and if it is, just pop down to the milk barn until it ain’t one!”

¤Anno (Deck 13 Epilogue)
Anno locks her gun back under her workspace and, in the same motion, shimmies out of the rest of her clothes, letting the well-worn catsuit drop to the floor. “We do (maybe 'did a') good work, boss,” she adds, walking over and planting a kiss on your cheek. “I’m going to hit the showers before I call the company and tell them what happened.”
...
“Slow... slow down,” she moans with fluttering eyelashes. Probing into her, you tease the tender inner walls of her cunt. Her muted protests are practically an invitation: you push another finger in and spread ‘em wide, letting the natural juice dribble down into the palm of your hand. Anno blushes and squirms as you tease her, leaving her neck open for you to kiss and nibble on. You drink deeply of her scent while you do; the heady mix of sex and sweat and her sweet, lavender (pretty sure her hair is white) hair leaves you breathless, desperate for more. Your fat, equine phallus pulls desperately against your Atma Armor Mk. I, swelling with your own mounting need. One of Anno’s hands brushes across it, gently cupping your turgid bulge and starting to tug you out of your gear. Breathless, Anno desperately pulls your Atma Armor Mk. I, undershirt, and plain briefs off to let it clatter to the floor before giving you a push through the bathroom door. 

¤Kaska (encounter) - Mispell
Keeping your bearings down here, surrounded by on all sides by endless rock, is a challenge. Doing it while your belly does backflips from the lack of gravity is a trial. Luckily you’re anchored to the metal platform by electromagnetic forces, at least as long as the batteries in the kit you picked up from the elevator last. More pressing is the bomb a few feet away. It’s not nearly as big as you would have expected a doomsday device to be, about as big as a bucket and equally visually appealing. Then again, all it has to do is destablize (should be 'destabilize') this station’s links to let the half planets' gravitational forces tear each other apart.

¤Kaska (Bad End) - Mistake
You were made to service Kaska three time more times (should be 'three more times') before making port. It was surprisingly easy; you just settled in front of her chair, opened up, and started sucking. The pirate crew might have been dining on food, but you never really got hungry, or wondered why. Once, when you started talking, Kaska pulled you onto her soft cock to give you something to do. It still tasted vaguely of her cum. It took over fifteen minutes of sucking to extract every ounce of flavor, but then she was leaking again.

¤Kaska (DickFuck) - Mispell
“No... I’m... an alpha...” Kaska weekly (should be 'weakly') protests as you bend her over a crate. Her dick, still leaking, is pointed straight down, pinned between her balls and the cool metal, and you get a good, long look at her pussy, for once not obscured by her troublesome maleness. It’s clear she’s a stranger to the feminine pleasures her body could enjoy, but that doesn’t stop her from being dripping wet, her lips slightly parted invitingly. The pirate’s pussy is just asking for a hard fucking.

Anno (Anal - Anno on top) - Mispell
You urge Anno faster, using your free hand to help lift her hind-end at the bottom of every bounce. Together, you’re making a chorus of sexy goans (should be 'groans') and low, sensual moans, rising toward the inevitable crescendo as your orgasms both approach inexorably, rushing forward to the point of no return. With a final cry of pleasure, Anno slams herself down on your rod, taking you to the hilt and wrist at once, and that’s all she wrote: you cum the moment you feel her cheeks press into your stallion-cock and large balls, blasting her bowels with a double load of held-back cum; her muscles go wild when she climaxes moments later, milking your cock for every last drop as her pussy tries to swallow your fist, trapping you in her spasming channel as she unleashes a torrent of fem-cum that leaves a puddle spreading between your legs.

**Comment by Fenoxo** [comment]
Fixt 4484f87deef1729af1c0889c473aa5760e52703f
