### ISSUE TITLE
Possible Typo: Steph @ Mhen'ga

### ISSUE THREAD

**Issue by Whatever-Kun** [Fenoxo/sourceTiTS#316]
"Ah, 'ere we go, see the cloaca engorging? When you hold em', naleen can't decide if you're tying to kill'em or mate with 'em! Let's get a closer look!"

**Comment by Fenoxo** [comment]
....what's the typo?

**Comment by Fenoxo** [comment]
...hrmmm, looks fine in code " kill 'em or mate with 'em "

**Comment by Fenoxo** [comment]
Derp. Got it via c32228a2334fbf714dcd81afccdcaa40a36ca84e
