### ISSUE TITLE
Dialogue tree for Xanthe sex scene has severed branch

### ISSUE THREAD

**Issue by MindDemon** [Fenoxo/sourceTiTS#317]
Xanthe has an issue in her sex scene where the player is supposed to make a choice as to whether she stays or leaves, but the menu is only populated with the stays option. Turns out the button id isn't incremented when adding the buttons to the menu, as quoted below:

    clearMenu();
    //[She Leaves You!] [Pays Attention] 
    addButton(0,"SheLeaves",getLeftByXantheSlooot);
    addButton(0,"SheStays",shePaysAttentionToYouSlut);

**Comment by Fenoxo** [comment]
Fixt via e8a4f5c995d5df994b7523f10c3ba8fb6fca0596

**Comment by Fenoxo** [comment]
Fixt via e8a4f5c995d5df994b7523f10c3ba8fb6fca0596
