### ISSUE TITLE
Perks/Levelup Buttons Not Displaying - Help Me Geddywon Kinobi

### ISSUE THREAD

**Issue by Fenoxo** [Fenoxo/sourceTiTS#318]
"On the sidebar panel, for some reason, the perksButton tooltip does not show. Same goes for the levelUpButton as well (unf, look at dat disabled statsButton). I assume something broke the bottom row of buttons from showing their tooltips. I can't find the exact bug causing it though, at least not yet anyway..."

-Jacques00, from this thread: http://forum.fenoxo.com/thread-12447.html

**Comment by Gedan** [comment]
Fixt.
