### ISSUE TITLE
Unused Gianna Lip Descript In Appearance

### ISSUE THREAD

**Issue by Fenoxo** [Fenoxo/sourceTiTS#319]
else if(gianna.lipRating() <= 4) 

I should investigate this later and see what's going on-^

**Comment by Gedan** [comment]
Handled in 2f31418

**Comment by Fenoxo** [comment]
Did you make sure the adjusted values match the types of texts for the swelling/shrinking texts? Cause they should match up.

**Comment by Fenoxo** [comment]
Double-checked and it looks good.
