### ISSUE TITLE
0.5.24 Myrellion Kaede typo

### ISSUE THREAD

**Issue by Kilth** [Fenoxo/sourceTiTS#320]
Inside Talon with Kaede:
Fuck ass: Double pronoun
“She she speaks, the white bubble at the tip of her shaft pops, drooling down over your fingers in a sticky wet mess.
Creampie/Facial: Stray brackets, appears on both scenes
"Instead, you slip out from between Kaede’s legs and flop back onto the couch{, watching gleefully as a trickle of your cum drools out of her well-fucked ass}."

**Comment by Gedan** [comment]
Fixt
