### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by cpt-jack** [Fenoxo/sourceTiTS#324]
v-ko electro stim scene
- She lifts what looks like an inflatable butt-plug and applies a liberal amount of lube to it, then walks towards you and does the same to narrow asshole. 

missing a "your" before the "narrow asshole."
- V-Ko procures one ring from her case and bring them over.

"bring them" => "brings it"
- Each of them vibrating and stimulating your as you begin panting in arousal.

either the "your" should be a "you" or the noun is missing
- The rod inside your cumvein don’t do anything but vibrate lightly either.

"don't" => "doesn't"
- All they can do is gyrate lightly.

"they" => "it"

kelly bar talk scene "my Mods"
- “Maybe we should try using those on my dick next time?”

"those" => "that" (only have one tail)
- You release her, withdrawing your tail from her abused holes.

"holes" => "hole"

kelly bar talk scene "share meal"
- In that that case, you’ll be looking forward to it.
minus one "that"

**Comment by Fenoxo** [comment]
Fixt 26c84bf705fc77845c06bd522922ec01e1a9b504
