### ISSUE TITLE
0.5.25 Lieve talk loop

### ISSUE THREAD

**Issue by Kilth** [Fenoxo/sourceTiTS#326]
Missing "Back" button when moving Lieve's room, unable to leave

Missing "Back" button when choosing Lieve's "Talk" option, causing inability to do anything else. Also, if talk is first interaction with her ever seems like "The war" does not proc path to "Scars?" and "Red prisoners?"

Under "Sex", there is no back button (for someone who miss clicked)
End of interactions with Lieve teleport you to Airfield 1F

When Sierva asks you to deliver letter, descriptions of "Alright" and "No" are mixed up

Save edited to add credits/experience, shouldn't matter to these but let you know just in case

Edit: added more bugs later, because worst and did not test out everything at first...

**Comment by Fenoxo** [comment]
Should be mostly fixed
