### ISSUE TITLE
[0.5.22] Mistakes a.k.a. Typos

### ISSUE THREAD

**Issue by Frahuenheld** [Fenoxo/sourceTiTS#327]
¤Jill & Shekka (Offer 20000/25000) - Missing space
Shekka peeps, mouse-like, and claps her hands across her mouth. The pressure of her excitement instead chooses to vent by making her tail wag, and it clangs noisily against the metal of the probe. “Really!?” she gasps. “You win. I can fix so many things on Novahome with all that cash!” The exuberant raskvel hugs(right here)you. “You’re the best!”

¤Anno as Follower (Suck&Fuck) - Mistake
Anno bites her lip, muffling a girlish whimper as your boyish hips rock forward, inching your sheath-girded dong into her sodden quim. You nearly join her as you feel your cock submerging into the sultry hole, surrounded by hot, wet, squirming walls as Anno’s pussy clenches around your intruding member. You push forward despite her body’s resistance, the ausar’s incredibly wet sex making it unnaturally easy to spread her walls wide. Anno moans as you plunge deep into her sex, fingers digging into the lip of her desk (should be 'bed' when she is a follower), tail flicking madly as you bottom out inside her.
...
Thanks to your recent orgasm and the minutes of pussy-eating that preceded your penetration, you’re soon greeted by the howling cries of Anno’s impending climax. You grin, slapping her cheeks and burying yourself deep inside your lover as she screams her pleasure, echoing in the store (should be 'room' or 'bedroom' when she is a follower) and down the corridors; her pussy clenches down hard, milking your animalistic prick for all its worth as she cums and cums, going crazy around your thrusting cock.

¤Reaha (Adiction) - Mising apostrophes
“Time to work on getting rid of those,(right here) you say, pointing to the pleasure patches stuck like stickers on Reaha’s thigh. She winces as if threatened, shifting her leg to cover the other, hiding the patches from sight. “I-If you say so...”

¤Saendra (Rescue) - Pretty sure I choose to park between Saendra and the pirates.
You put a hand on her good shoulder, then book it back towards the airlock. Now that it’s back online, you fix your suit back together and cycle through the airlock. When the outer door slides open, you’re greeted by a light show as the Phoenix's shields buckle and flash under bombardment, and stray shots go wide around the drifting vessel, lighting up the darkness of space. Thankfully, Saendra’s ship is still parked between the pirate vessel and your own, shielding your ship from the worst of the attack. You grab the rope connecting your ships and hit your thrusters, hurtling back across the gulf of space and into your still-open airlock.

¤Shekka (Fuck Her) - Mispell
Shekka, usually sassy and quick to react, looks at you uncertainly. Her tail swishes back and forth nervously, but she does as you ask, grabbing parts from all over her workbench into a smile (should be 'small') pile before you. A moment later, her confident smile returns. She presses her large rump back against you, curling her tail around your side so as not to interfere with the soft, sensuous press of her buttocks against your package. With just an earnest flex, her cheeks squeeze your stallion-cock harder.

¤Jade (Titfuck) - Mispell and missing word
“Atta boy,” Jade moans back at you, visibly shuddering from the friction. “You like this, doncha?” She kisses and slurps at your equine glans, polishing you with long, wet licks, laying them on you with every downward slide she takes. Emerging from your cum-slit like a precious pearl, the first droplet of pre-jizz leaks from your enjoyment inundated system. It rolls down the bottom of your manhood, sped (What is sped? Maybe 'spread') along by the shining moisture you’ve accumulated. She’s happy to catch it in her tits and bounce a little harder... and a little faster, making you that much firmer and that much more eager.

You cannot remain passive any longer. Your heart is beating like crazy. Your fat, flared stallion-cock is absolutely demanding you (to) sate your pent-up need. Lurching forward, ...

¤Jade (Suck Nipples) - Understatement. Just my opinion.
Jade grins a knowing grin at your suggestion. “Of course, Maximilian; go ahead,” she tells you, thrusting her ample bosom towards you and beckoning you with a crooked finger.

¤Nehzara (Talk > The War) - Missing aphostrophes.
(Right here)When we engaged and tried to see them off, our pilots came under attack. Of course, the bastards later claimed their pilots were not under orders to fire, but that’s nonsense and we all know it. We already knew they’d been developing a new delivery system for that gas of theirs. One grueling campaign later, Kressia is ours and Gildenmere is in our sights. And then you showed up.” Her tone turns bitter at that last sentence, but she’s not looking directly at you: instead, her gaze is fixed firmly on a point just to your left.

¤Nezhara (Talk > Her people) - Possible mistake.
Nehzara shakes her head in a universal gesture of exasperation. “Sounds about right for Lyralla. That brainwashed, spineless nectar-guzzler spends every waking moment trying to convince everyone that we’re nothing short of evil given form. Well, any moment her lips aren’t wrapped around a swollen honey-spout. I could swear the stuff kills their brain cells. So she’s cried on your shoulder and given her usual cockamamie spiel about how the heartless Reds eat babes (Maybe 'babies') and kill prisoners for sport?”

¤Lyralla & Juro - Mispell
“Relax. No one will be looking for us for another hour, and this closet is for my personal archives. Our assistants would never come in here without our permission. Besides, even if someone did see us slip in, it wouldn’t be inappropriate for me to be discussing the ancient treaty of Terrai over lunch in here.” Juro pauses to moan and step a little closer to his ant-like lover, pressing the fullness of his erection against her belly. Any closer and his face with (should be 'will') disappear into her breasts. “Right there....”

¤Shade (Talk > Runes) - Mispell
“Am part,” Shade corrects with a little smirk, pulling a small, silver necklace out from her shirt. It looks like a vertical bar pierced by a triangle, sort of like a sideways hat. “I told their leader I didn’t buy into the whole gods and giants thing, but he just smiled and (I think it should be 'at') me and nodded, all fatherly understanding. Said belief wasn’t what mattered, but the way you behaved. He told me about their philosophy, honor in battle, wisdom before action. They preached self-empowerment and courage more than gods; hell, some of the oldest members confessed to me while I was there that they didn’t believe in the gods, but they liked the message. I suppose I could have picked a worse religion to fall in with than one that encouraged me to be a warrior, even trained me. Plus they had a pretty serious fertility and sex-potency undertone going on, so it didn’t hurt that I came to them with a kid on the way.”

¤Embry - Missing aphostrophes.
“U-um, here’s your menu, so you can drink or eat. Eat the food on the menu - not the menu itself,(right here) she rambles. “... If you’re hungry. I mean, you don’t have to. I’m not going to force feed you or anything.”

¤Embry (Mock) - Missing aphostrophes.
Embry eyes start quiver as if she’s going to cry. She drops the menu, and pulls her hands up to her mouth. “... I’m – I didn’t mean to... I’m sorry!(right here) She turns on the spot, and moves to dash off.
...
“The myr girls around here go crazy for anything that looks like a guy so, please, don’t tell anyone...?(and right here)

**Comment by Frahuenheld** [comment]
Bwahaha I’m so evil hahaha. -Anno

¤Embry (Don't Love You) - These three pharagraph are on italics or at least that's what I see in Android.
Embry moves towards you and reaches out to touch you, and you push her hand away. She recoils like a kicked dog, whimpering pitifully and falling to her knees.

You’re acutely aware of the bystanders now looking at you both, watching the awkward and dramatic public scene. The simii girl looks utterly distraught as she trembles and rocks on the ground.

You cough and tell her it’s over, since it seems like the time. Her wailing intensifies. Eager to escape the spectacle before someone gets involved, you hurriedly head back to the elevator, leaving Embry crying on the street. That was never going to go well...

¤Embry (Pitch Anal) - Bullshit! I already popped her cherry e_e
“Um, you know, we’ve... n-never really had sex, you know? Not like, for real. I’m always pleasuring you, or you’re pleasuring me, but we’ve never really done it, you know-?” Embry boldly states, though her eyes are looking down at her feet. “... I-I was thinking, maybe, you want to use my ass—?”
...
“U-um, my butt feels kind of sore, but I feel really, REALLY happy.” Your simii lover’s fingers trail across your naked breasts (I think 'flat chest' would be more aproppiate for male pc), drawing cute little circles. “... I loved having you inside of me. And I’m glad you’re the one who took, you know, my virginity - at least of my butt,” she blushes.

¤Embry (Breast Play) - Missing aphostrophes.
“I-I never knew I could cum like that... until you. You’re amazing... she breathily tells you,(right here) her cheeks flushed. “... But I love this bit the most; being in your arms afterwards.”

¤Embry (Analingus) -That i should be on capital.
When it’s clear this is going to happen, she gets down on her knees, and puts her slender hands on your buttocks. “... O-okay, tell me if i(right here)’m doing it wrong...” she slowly parts them and stares at your puckered hole. You cheekily flex it, and she lets out a little gasp. Her face inches closer to your rim, and you can feel her burning cheeks brushing against yours.

¤Liliana (Cuddles) - Mispell
Between you and the cloudy softness of the bed it doesn’t take long before she’s breathing gently in your arms, her grip softened in the relaxation of sleep. For a few minutes you wonder if she’ll sleep soundly tonight just from your presence, and begin to drift off into your own slumber. You’re interrupted by her breathing becoming a little quicker, and you feel her heart beating in her chest faster than it has any right too (should be 'to') during sleep. Her grip re-tightens and she whimpers at unseen distresses. You hold her tighter, brushing the back of her hair to help calm her down.

¤Shade (Sex > Cuntail) - Mistake
“Juuuuust like that, kid,” Shade groans, grinding against your face, shivering from tail-tip to toe around your probing tongue. You grip her tighter, refusing to let her move too quickly - you’re going to enjoy this too, damn it! Your tongue slips deeper into her, slithering through the tight channel of Shade’s sex, lapping at the sweet juices that bead out in answer to your every motion. Shade’s mounting excitement translate in a steady increase in her tailcunt’s pace, making it’s slitted tip bounce on your shaft. She echoes “Just like that,” again and again, stroking your moderately long, black hair with one hand, cupping and squeezing her breasts with the other, giving you a chance to finally see your lover’s face again. Her eyes are rolled closed (so... they are rolled or closed?), mouth agape with silent cries of pleasure.

¤Renvra (Sex) - Mispell.
Ren breaks the kiss a moment after you free her shaft, grinning up  at you. “So, what’s it going to be, spacer? Want a piece of my ass, or are you thinking about a (should be 'an') ass full of this bad boy?” she teases, stroking her massive prick.

¤Xanthe (First Encounter) - Missing aphostrophes.
Noticing your puzzlement, realization dawns on the alien woman. “Oh! It’s your first time meeting a siel. And here I was thinking you were just that interested... what a shame.(right here)

¤Xanthe (Use Mod > Half Close)
You notice her dark blue nipples are slightly crinkled and her puckered buds are becoming stiff before your eyes. You can’t tell if it’s the cold or from stripping in front of you, a (this 'a' should be replaced with 'an' when PC is ausar) ausar she clearly finds attractive, whether you’re looking or not.

**Comment by Gedan** [comment]
>Saendra (Rescue) - Pretty sure I choose to park between Saendra and the pirates.
"you angle your ship around beneath the <i>Phoenix</i>, putting it between you and the pirate vessel" - this is the only option to actually board the Phoenix iirc.

**Comment by Frahuenheld** [comment]
Went all the way with Spend Time after giving her 15000 credits and telling her I dislked dicks.

**Comment by Gedan** [comment]
Yeah, which scene under that. 'Spend Time' points to like 50 different scenes. I need the actual scene; preferably some text from it, so I can find it easily.

**Comment by Frahuenheld** [comment]
Ok, I'm trying to emulate that path and every other just in case and going report any discovery on a new issue. Btw, there happened something strange: After I gave her the first 5000 credit tip she offered me to witness the transformation. When I was interacting with her for the first time and gave her the tip, the next scene just played the one when you enter the bar and see her a little more girly not the "witness" scene.

**Comment by Frahuenheld** [comment]
So, I had tried several different paths and all of them is the same. Maybe that dialog of Embry only works with an anal-virginity-flag and without a flag for vaginal virginity.
Dialogs in Blowjob's scene work fine, btw.
