### ISSUE TITLE
Dissappearing genital and renvra belly descriptions.

### ISSUE THREAD

**Issue by virado** [Fenoxo/sourceTiTS#328]
Descriptions for what I think are the vagina have disappeared

Example is a  sex scene with a Nyrea but not limited to just this

You bring a little of that sweet, warm moisture out to rub down on the outside of her prick. It’s not much, but you’re confident your null will thank you for it soon.  

Character has multiple vaginas.

Also no descriptions are being changed regarding the stomach when carrying Renvra's eggs

**Comment by eldestdawn** [comment]
also happens with male only characters.

**Comment by Gedan** [comment]
Gotta include version numbers in your reports; I'm pretty sure I tweaked this for the latest backer release...

Also, there were no variations written for Belly description for her pregnancy, so yeah, you're just getting a single message.

**Comment by virado** [comment]
Sorry about that this was written as of 5.25 and I meant the players belly. i don't remember which patch it was but when Renvra originally came out and the player was carrying her eggs there would be a description of the players belly. A few patches later up till now (5.25 havnt 5.26 as of writing this) I only get the flat belly description.

**Comment by Gedan** [comment]
She actually has two different pregnancies; one does vary the belly descriptions, the other does not.
