### ISSUE TITLE
[0.5.22] tavros.reaha.expansion bugs and typos

### ISSUE THREAD

**Issue by cascet** [Fenoxo/sourceTiTS#329]
You can start addiction therapy without ever taking Reaha to New Texas and talking about it to her. Bug?

Other things:

line 103:
if (9999 == 0)  ->  ???
(if PC got treatment? if High lust?)

line 322:
<i>“Just... do whatever you came here to do, and let’s leave. Okay? I don’t want to be here a second longer, [pc.master]. This planet makes me sick!”</i>"
(1. Reaha pleads leaving the planet even when not on New Texas.
2. [pc.master] should probably be differentiated? Or the author intended to always use pc.master here, hard to say.)

lines 337/340:
if (9999 == 0)  ->  if (shipLocation == "500")

line 341:
" Tee’s ranch"  ->  " T.’s ranch" 
(consistency)

lines 454/455:
if (!reahaFree()) output(" suck dick");
else output(" be your personal milk maid");
(Should this be switched around?)

line 718:
output("s");  ->  output("es");

lines 780/809:
five foot nothing of athletic, well-toned human woman.  ->  five foot of nothing but an athletic, well-toned human woman.

line 958:
if (9999 == 0)  ->  ???
(if feet human?)

line 1059:
of your [pc.lowerUnderGarment],  ->  of your [pc.lowerUndergarment],
(displays "null" otherwise)

line 1135/1398:
if (9999 == 0)  ->  ???
(if reaha nude?)

line 1538:
if (9999 == 0)  ->  ???

**Comment by Gedan** [comment]
> five foot nothing of athletic, well-toned human woman. -> five foot of nothing but an athletic, well-toned human woman.

Nothing wrong here- 'five foot nothing' is another means of saying 'exactly five feet tall' p. much.
