### ISSUE TITLE
[0.5.22] Mispells and bugs 2.0

### ISSUE THREAD

**Issue by Frahuenheld** [Fenoxo/sourceTiTS#330]
I'm going to try reporting by tracking the errors in the code so it's easier for the one fixing them. Hope I do it alright :P 
If someone wants to teach me how to create a pull I could do that so you can just analyze it and merge if everything is ok. Of course, I would keep reporting on issues the flags in cases like the first report in here.

Shekka
Line 485: if(flags["TARKUS_DESTROYED"] == undefined) -> = 1
This dialog plays before going to the Stellar Thether and after saving Tarkus.

Kiro
Line 158: "Fuck the beached Tankuis cunt." -> "Fuck the beached Tanuki's cunt."
Mispell and missing apostrophe.

Line 168: "Ride the Tanukis monster cock." -> "Ride the Tanuki's monster cock."
Missing apostrophe

Line 172: "...you could ride the Tankuis monster cock." -> "...you could ride the Tanuki's monster cock."
Mispell and missing apostrophe

Line 320: [pc.oneCock]
This flag described my feline cock as "your pink, pink shaft"

Kelly
Line 394: output("\n\n<i>\"And is that such a bad thing,\"</i> -> output("\n\n<i>\"And is that such a bad thing?\"</i>
Missing question mark at the end of the dialog.

Line 857: flying away to the floor. \"Oopsie,\" she giggles."); -> flying away to the floor. <i>\"Oopsie,\"</i> she giggles.");
That little dialog isn't on italics.

Line 3386: You want her to tease her until she’s a screaming pile of oversexed bunny.");
The first her is superfluous or the second her should be 'her pussy'.

Embry
Line 1497: output("You tell [embry.name] it’s not a choice -> output("You tell Embry it’s not a choice
You're not supposed to know which name she will choose.

Line 1888:  She seems understanding, though very embrassed."); ->  She seems understanding, though very embarassed.");
Mispell.

Herman (texasNew.as)
Line 1100: output("You give herman your order, -> output("You give Herman your order,
Just the name.

Millie
Line 592:  Besides, if there’s one thing you can trust cow-girl on, ->  Besides, if there’s one thing you can trust (a) cow-girl on, "OR"  Besides, if there’s one thing you can trust cow-girl(s) on,

Flahne
Line 872: output(" She stammers, “I-I... I... ummm... I’ll be back later! Sorry!”</i> -> output(" She stammers, <i>“I-I... I... ummm... I’ll be back later! Sorry!”</i>
The dialog isn't on italics.

Yammi
Line 652: The do enjoy warm flesh after all the cold machines. -> They do enjoy warm flesh after all the cold machines.
Mispell.

Reaha (tavros.reaha.expansion.as)
Line 693: output("I grew up on New Texas, okay?  -> output(<i>"I grew up on New Texas, okay? 
This dialog isn't on italics.

Line 777: and a much darker complexion that Reaha. "); ->  and a much darker complexion than Reaha. ");
Mispell.

Line 1609: output("\n\n<i>“I’ll see you see, I guess,"); -> output("\n\n<i>“I’ll see you soon, I guess,");
Mispell.

Queen Irellia
Line 437: Sure, you seen a lot more variety out there, -> Sure, you have seen a lot more variety out there, 
Missing word.

Line 572: from the top of her surprisingly-engorged clitorus, -> from the top of her surprisingly-engorged clitoris,
Mispell.

Nuki Cookies
Line 218: kGAMECLASS.output("\n\nAt itch radiates out -> kGAMECLASS.output("\n\nAn itch radiates out
Mispell

Horse Pill
Line 193: "You adjust your package and fine -> "You adjust your package and find
Mispell.

Line 527: before realizing that its grown. -> before realizing that it's grown.
Missing apostrophe

The Treatment (classes/Items/Miscellaneous/Treatment.as)
Line 3: /includes/treatment.as 	-> /includes/texasNew.treatment.as
I got lost because of that.

The Treatment (includes/texasNew.treatment.as)
Line 1114: You’re either going to need to give them some attention, -> (if multiple cocks) You’re either going to need to give them some attention, "AND" (if single cock) You’re either going to need to give it some attention,

Line 1191: This Treatment this is working out pretty great."; -> This Treatment is working out pretty great.";
The second 'this' is superfluous.

Line 1764: else eventBuffer += ", and your others aren’t far behind";
This line appeared to me when I only had a penis.

Line 2184: 	if(pc.hasCock()) eventBuffer += "es";
The same as above

P.S: And don't forget to check my last comment on #327 where I put a possible solution for Embry.

**Comment by Fenoxo** [comment]
Fixt c19130d8de4b962963d343b6af5ee9e984ee92ea
