### ISSUE TITLE
[0.5.28] Public - Debug is not getting disabled when loading a Save Game

### ISSUE THREAD

**Issue by NeitherMeNorYou** [Fenoxo/sourceTiTS#333]
As the subject says, if you have a save game with debug enabled, and you load it into 0.5.28 the debug flag is not cleared.
This wouldn't be too big of a problem but after saving the game, thinking it got disabled on its own, I found out that this wasn't the case, and now the flag is stuck.
The "new" save file is also incompatible with older game versions, making it impossible to change the debug flag, except through save editing.

**Comment by Fenoxo** [comment]
Load in an older version, turn it off, and never again mess with it.

**Comment by NeitherMeNorYou** [comment]
I tried that, gave me an null error.

**Comment by Fenoxo** [comment]
Type "fuckyou" into the game. Please don't spread it around.
