### ISSUE TITLE
And I still didn't play 0.5.28

### ISSUE THREAD

**Issue by Frahuenheld** [Fenoxo/sourceTiTS#335]
<b>Puppy Slut-mas</b>
Line 103
My pc has Hard Attitude (called Ass in the code for some reason) and the game showed this line. Don't know if it's supposed.

Line 550: “I bet you did!
Just to confirm. Shouldn't it be “I bet he did!"?

Line 1004: reaching in the (should be 'to') kiss her.
Mispell.

Line 1127: " Slow isn’t really my style... but for you, I guess I’ll make do.”</i>");
This dialog isn't on italics.

Line 1325: output("\n\nMrs. Dorna’s eyes light up at that, and her father gives you an
Shouldn't it say: "her husband"?

Line 1360: each with a belt of cutlery slung on his ore her, and make their
"On his OR her" what?

<b>Kelly</b>
Line 309: She moans plaintively. \"[pc.short], seriously... we can't... I can't get caught,\"</i>
This dialog isn't on italics.

<b>Rival and Shekka</b>
Line 3086
I avoided contact with Shekka before this scene and it still plays the one where she accepts the 16000 credits.

<b>Gray Goo</b>
Line 21: \"Gray goo detected. These active micro-machine clusters are known to attack without provocation. U.G.C. Scout Authority suggests extreme caution, as well as hydration, around the native goo.\"");
I think it should be on italics. By the way, the scene with the Codex plays everytime I meet a Gray Goo.

Line 406: leaving you a helpless, sexually exhausted heap on the group (should be 'ground').
Mispell.

**Comment by Frahuenheld** [comment]
<b>Penny</b>
Line 2236
I think the flag there is wrong.

Line 2275: polishing your [pc.cockBiggest] with with its own juices.
Double 'with'.

Line 2850:  “Ahh, f-fuck, eat me like the predator you are, Steele,”
This dialog isn't on Italics.

Line 2865: “Huh? It’s not over? I don’t know how active I’ll be-eeee”
Same as above.

And now that I played 0.5.28
<b>Kaede on Myrellion</b>
Line 475: the halfbreed dog-girl’s claws caress
Shouldn't be 'fingers'? I mean, as half-ausar she has human hands.

Line 512: until the climactic cumshut (should be 'cumshot') trickles down
Mispell.

Line 545: output("A wicked through (should be 'thought') crosses your mind,
Mispell.

<b>Merchant Queen</b>
Line 58: Now then, how many (should be 'may') I help you?
Mispell.

Line 251: Rationing spurs up unrest much more then (should be 'than') some strict rules backed by bullets
Mispell.

Line 254: Just bred (should be 'breed').
Mispell.

**Comment by Frahuenheld** [comment]
Trying new things while looking at the code.
<b>Lieve</b>
Line 138
There is missing the ”</ i> at the end of the dialog.

Line 310
There is missing the ”</ i> at the end of the dialog.

Line 407
There is missing the ”</ i> at the end of the dialog.

Line 420
There is missing the ”</ i> at the end of the dialog.

Line 537: “If you don’t mind my asking,
Just to confirm, shouldn't it be "mind me asking"?

Line 559
There is missing the ”</ i> at the end of the dialog.

Line 850
There is missing the ”</ i> at the end of the dialog.

Line 1337: Look, we can have some fun by proxy, though (should be 'through') the girls, alright?
Mispell.

Line 1792
There is missing the ”</ i> at the end of the dialog.

**Comment by Frahuenheld** [comment]
<b>Naleen</b>
Line 568:  but a moment later and she's purring happily,
That "and" is superfluous.

Line 915:  causing her (to) drool.
Missing word.

<b>Siry</b>
Line 637: “What.” -> “What?”

<b>Vanae</b>
Line 1225: Once she has finishes appraising your [pc.cock " + selCock + "] she stretches out her
I think the times are wrong.

**Comment by Fenoxo** [comment]
Fixt via 92ecd7f755b7088d82d4828856030ac4c0e72a36
