### ISSUE TITLE
Where'd the zil go?

### ISSUE THREAD

**Issue by eldestdawn** [Fenoxo/sourceTiTS#336]
I have been through the jungle on mhen'ga multiple times and the zil have disappeared. all i run into is the frog girls, naleen, and cunt snakes for combat. i have spent multiple in game days running through the jungle and have yet to see a zil. this is on a new game with the latest backers build. 

i believe the problem is with the frog girls. because there are so many different frog girls, their encounter rate has put them before anything else which makes finding other species harder. the frog girl encounter should be the roughly the same as zil or naleen.

**Comment by Fenoxo** [comment]
Load up your game in an older version of TiTS, disable debug mode, and never again turn it on.
