### ISSUE TITLE
[0.5.28] Public - Bugs in 'Ride Cock' Victory scene Nyrea Huntress with Eggs

### ISSUE THREAD

**Issue by NeitherMeNorYou** [Fenoxo/sourceTiTS#337]
This concerns the Ride Cock Victory Scene after defeating an Nyrea Huntress / Beta Nyrea who carries eggs.

(I followed Fenoxo's hint and successfully turned off debug mode on my savegame, thanks for that)

**Bug 1**: Taking the ovipositor up the ass in this scene will display it as being in an vagina in one paragraph.
**Bug 2**: Taking the ovipositor up an vagina, if the ass has been successfully filled with eggs, results in 0 deposited eggs and no pregnancy.

If it helps, the test character has 2 vaginas.

-----

Excerpt for the first bug:

> You shudder and moan as the sheer, soft surface of the egg crowns into you, brushing your inner walls. The nyrea’s cum acts as lube, allowing the egg to slide into you with merciful ease. The egg lodges in you, held in place by your own clenching muscles and the sickly sticky lube she’s sprayed into you, filling your ass with alien spooge and egg.
> 
> And then another egg starts making its way inside you, pushing the first even deeper, filling your **cunt** with egg after egg... you count as at least 6 eggs that eventually swell your belly before the nyrea runs out of ammunition, and her knot deflates enough to allow you to slump off of her. Listlessly, you collapse onto the ground, rubbing your swollen belly full of eggs.

**Comment by Fenoxo** [comment]
Fixt the first part. I think the second is intentional.

194f645f8c67f468ad80a3b5a43a95712cab6345
