### ISSUE TITLE
[0.5.28] PUBLIC - Skysap transformation (ERROR: NO WANGS DETECTED)

### ISSUE THREAD

**Issue by WightKitty** [Fenoxo/sourceTiTS#338]
This report concerns a bug/glitch whereupon taking the transformative "SkySap" while endowed with a small penis will result in an error.

(No debug mode)

Excerpt;
---------

[...]

You run your hand along your freshly formed skin and shiver a little with delight. You now have pale orange skin!

Deep in your lower abdomen, you feel a hot pooling sensation growing and coiling tight. You rub your belly, moaning as it steadily intensifies. Soon you’re on the ground touching between your thighs, stroking a place that is now becoming incredibly hot. It feels like you’re about to cum, but not from your ERROR: NO WANGS DETECTED for cocksDescript()!

[...]

You now have a virgin, luminous orange vanae pussy and two clits — you’re also a squirter!

You feel a tingling along your thin, kitty shaft and a slight withdrawal back into your skin. Looking down, you realise your kitty kitten-prick has disappeared! You no longer have a kitty-prick!
(A/N: Kitty kitten-prick?)

In addition, the disappearance of your only manhood also seems to affect your prostate... With rhythmic pulses, the size of your package gradually diminishes until it vanishes completely! You no longer have gonads!

**Comment by Fenoxo** [comment]
Fixt 84083d3caddd8f16e7d666fed68f51ae95c57685
