### ISSUE TITLE
Cannot progress Venus Pitcher while genderless and no tail

### ISSUE THREAD

**Issue by Bjoob** [Fenoxo/sourceTiTS#341]
The Large Venus Pitcher page is unable to progress or quit when the captured player has no genitalia, including tail-cunt. If the player has no normal genitalia, but does have a snake-cunt, the text will progress normally. The text progresses normally for the Small Pitchers either way.

**Comment by Fenoxo** [comment]
Fixt via 25e8638e1ed51a9092d367d54f06a41b1145b654

Genderless untailcunted can no longer encounter them.
