### ISSUE TITLE
[0.5.28] "Sink In" Celise option has a null in it.

### ISSUE THREAD

**Issue by BobTheLost** [Fenoxo/sourceTiTS#342]
The Null is half-way down the page at the paragraph that starts with “Whoopsie,”. If it helps my character is a female human, with honey girl-cum.

"Your null are painstakingly covered in a layer of warm, thick Celise, stopping just short of the areolae. Errant strands of goo creep from the rings to tweak and moisten your exposed nipples as Celise playfully bites your ear muster a dribble of milk to answer them."

**Comment by Fenoxo** [comment]
Fixt c20d904d5448533fe9b7b90853a2a05a5916ad92

**Comment by Fenoxo** [comment]
Fixt via c20d904d5448533fe9b7b90853a2a05a5916ad92
