### ISSUE TITLE
5.28 typos/bugs

### ISSUE THREAD

**Issue by Feralcus** [Fenoxo/sourceTiTS#343]
Male zil - get BJ
in this jungle.>>>>>Calmy,<<<<

	Syri >bet yourself>win>fuck ass--Shouldn't it be "knotted"?
from the base of her knotting red pecker 

	Lane
throws you onto the bed, face down and bent at the waist, >>>>your null exposed<<<< and winking

pussy, you whimper in need. >>>>“You sound... needy. Lane,<<<< already leaning--Needs quotes.

His grip gets tighter, and he drags his claws over >>>>your null painfully<<<< as a consequence.

and he drops his feet to the >>>>floor. he regulates<<<< his----Needs capital.

	Sydian male>encounter text
>>>>The creature cocks dusts itself off<<<< as it regards you,

	Raskvel male trio>combat loss
as he clenches up once and with a breathless grunt fills your >>>>guts/womb<<<< with liquid warmth. 

propel fresh cum into your >>>>softened pussy and sucking maw<<<<---- At this point wasn't the one using your ass not your pussy?

	Newtexas>male milker
>>>Carries<<< lays it all out on a----Should be "Carrie"

	Shekka>talk>herself
boys into swelling >>>me up more<<< eggs.” ----Missing a "with"?

**Comment by Fenoxo** [comment]
Fixt 23014974c1bc6eb81d35f29c8cd7813ef629dd30
