### ISSUE TITLE
[0.5.28] Missing italics when entering Tarkus

### ISSUE THREAD

**Issue by Frahuenheld** [Fenoxo/sourceTiTS#345]
At the end of this scene the pc says/thinks "Goddamn the ship is prehitoric!" and this text is not on italics. And maybe it should be better: "Goddamn, the ship is prehitoric!" or "The goddamn ship is prehitoric!"

**Comment by tmedwards** [comment]
Beyond that, `prehitoric` should be `prehistoric`.

**Comment by Frahuenheld** [comment]
Damn, you are right.

**Comment by Fenoxo** [comment]
47e5414f94f38404943e463183178b9a764e4dbf
