### ISSUE TITLE
[0.5.28] texasNew.millie bugs and typos 

### ISSUE THREAD

**Issue by cascet** [Fenoxo/sourceTiTS#346]
flags["TRIED_TREATMENT_LIGHT"] is still not defined after using faux treatment

pc.cockChange(); is missing in millieMilkersPartDues() and milliePersonallyDrainsYerTiTS()

In millieSucksTitsVol2() the parts with Temporary Treatment are unnecessary, since the Faux Treatment automatically leads into millieMilkersPartDues(). If they need to be left in for some reason there are still typos I noted below.

Other things:

lines 98/100:
output("< i >“ -> output("

line 230:
, please"); -> , please.");

line 307:
, and her engulphing of "); -> , and her engulfing of ");

line 417:
if(pc.totalBreasts() > 1) output("s"); -> if(pc.totalBreasts() > 3) output("s");

line 430:
if (pc.isLactating()) -> if (pc.isLactating() && pc.milkType != GLOBAL.FLUID_TYPE_MILK)
(to prevent "smells like milk, milk, and cherries")

lines 457/982:
pc.breastRows[0].breastRating -> pc.breastRows[0].breastRating()

lines 460/462 and 985/987:
pc.breastRows[0].breastRatingRaw -> pc.breastRows[0].breastRatingRaw()

line 583:
hope up onto -> hop up onto

line 600:
if(pc.cockTotal() > 1) -> if(pc.cockTotal() > 2)

line 765:
output("shrug and pop them on in."); -> output("shrug and pop them on in");

line 893:
feeling are overwhelmingly -> feeling is overwhelmingly

line 937:
attension -> attention

**Comment by Fenoxo** [comment]
Fixt via 7ed5650f4f87398b60eb2d6bfed33303e420a339
