### ISSUE TITLE
sumited but loss screen

### ISSUE THREAD

**Issue by ericmonkee** [Fenoxo/sourceTiTS#350]
just came upon a Kerokoras and I submit but I got the lost screen as if I fight her.

The lithe frog-girl walks around your helpless body, appraising her prize carefully. She makes a few short hops over to you and presses your weakened frame down onto the ground, evidently having made her decision.

You look at the smiling kerokoras, who looks back at you with hopeful glee. Her hands hold your weakened arms steady as she leans in close to you. “I’m sorry you had to lose, but you don’t have to be grumpy about it.” she says, mockingly pouting in front of you. Her long tongue tumbles out of her mouth and onto your neck. You tense as she licks upward, covering your face in drugged saliva. Your vision blurs as your reason is overwhelmed by slowly growing lust.

p.s. sorry if I did not give u some thing u all rdy know

**Comment by Fenoxo** [comment]
Fixt via eff39fae8300284cde21ad560b66915a1c703a2c
