### ISSUE TITLE
Hand So ending bug?

### ISSUE THREAD

**Issue by littlebeast** [Fenoxo/sourceTiTS#355]
So after the fight with Hand So, I go to the left console to try to download her.

This time, I got a message I've never seen before.  A snide comment about "dl crazybitch.exe" and failed to get the bead.  Okay, this is clearly intended, not sure why it showed up then though, especially since it didn't after loading and doing the same thing, just random?  Whatever, that's irrelevant.

**The bug is**, after getting that ending, while walking around the map I get the message, "You're still in combat, you ninny!"

**Comment by Fenoxo** [comment]
First part is due to failing a skill check roll.

Second is definitely a bug.

**Comment by Fenoxo** [comment]
Fixt via d22e07dd265b21fe9fcbf471cc0e5e66f5cd26f3
