### ISSUE TITLE
Machina Bug From Emails

### ISSUE THREAD

**Issue by Fenoxo** [Fenoxo/sourceTiTS#358]
i was playing game when on first plan to find robot in vally to get gun this pop up.

You land a hit on the machina with your machete! (4)

You hear a loud whir from the corrupt machine before it jerks forwards, coming at you as the main body starts to rotate. Not too soon after it is spinning at a blur of a pace, appendages sprawled outwards and in range of you! Watch out!

Something bad happened!

Please report this message, and include any prior scene text or a description of what you did before seeing this message:

Version: 0.5.30

ReferenceError: Error #1069
    at classes::TiTS/theSpinner()
    at classes::TiTS/machinaAI()
    at classes::TiTS/enemyAI()
    at classes::TiTS/processCombat()
    at classes::TiTS/playerAttack()
    at classes::TiTS/attackRouter()
    at classes::TiTS/buttonClick()

i dont know what i did wrong but good game. love it.

try send it by follow like to report glitches or errors but couldnt

**Comment by Gedan** [comment]
Fixt.
