### ISSUE TITLE
Embry bugs

### ISSUE THREAD

**Issue by coladict** [Fenoxo/sourceTiTS#365]
In the cunnilingus scene:
> The monkey girl strips off your null.

Also, after changing her name, it still says Embry on the icon.

Here's a link to the save https://www.dropbox.com/s/19epjsm0nc8r7fo/TiTs_1.sol?dl=0

**Comment by Fenoxo** [comment]
Fixt via ef71ad986d3ba3c705463944797776bbcc07cef8

**Comment by coladict** [comment]
That doesn't fix the name, though. Have you tried replacing the line in showEmbry from

    	showName("\nEMBRY");
to

    	showName("\n" + embry.short.toUpperCase());

I tried building the source, but the fl.motion.Color class is not available in Flex SDK. It's Flash-only.

**Comment by Fenoxo** [comment]
Good to go.
