### ISSUE TITLE
Renvra Pregnancy

### ISSUE THREAD

**Issue by JohnCollins5091** [Fenoxo/sourceTiTS#369]
Renvra bug is still active in 0.5.32
Just in case it’s still unknown.
BTW it’s not the one where the pc gets full of fertilized eggs, but when the pc gets actually impregnated (the one where you get a few events of puking before getting the event where the pc realizes it’s pregnant).
The bug: After going through the whole pregnancy, the game still thinks the pc is pregnant, and you'll constantly get pregnancy events, including infinite milk production, even though you're not pregnant.
I've also taken the liberty of taking screenshot for you to see.
![screenshot_clientversion](https://cloud.githubusercontent.com/assets/12280148/7501480/6bf09402-f3f1-11e4-8ae2-f42075c71245.png)
![screenshot_renvrasexoption](https://cloud.githubusercontent.com/assets/12280148/7501476/6be5de7c-f3f1-11e4-9df5-ef12deb0e48a.png)
![screenshot_birthevent](https://cloud.githubusercontent.com/assets/12280148/7501477/6be69538-f3f1-11e4-9902-9f746ac4cd80.png)
![screenshot_bugevent](https://cloud.githubusercontent.com/assets/12280148/7501478/6be9e88c-f3f1-11e4-8e2c-52425cf96d27.png)
![screenshot_notpregnant](https://cloud.githubusercontent.com/assets/12280148/7501479/6bedd4ec-f3f1-11e4-9a78-f4ea498ff2d3.png)

**Comment by Fenoxo** [comment]
Yeah I managed to chain two births back to back, though the second one I never got belly rubs. Weird.

**Comment by Gedan** [comment]
a11227b

:|

**Comment by JohnCollins5091** [comment]
Code typo?

**Comment by herp-a-derp** [comment]
> Code typo?
Code-O!

**Comment by JohnCollins5091** [comment]
Heh. Heheheh
Lol.
