### ISSUE TITLE
Shelly not taking virginitiy

### ISSUE THREAD

**Issue by Spectrumofchaos** [Fenoxo/sourceTiTS#371]
When sexing Shelly, the bunny-girl in the Anon's Bar on Tavros, you don't lose your virginity.

**Comment by Fenoxo** [comment]
Note: this would be much faster to fix if you included a snippet from the
scene in the bug report.

**Comment by Spectrumofchaos** [comment]
My apologies. Here is the first few sentences from the scene:

You ask Shelly if she’d be up for a little more than just egg-laying assistance. She looks confused for a moment before realization lights up her face.

“Really? You’d do that, with me?” she asks, obviously happy but not totally sure.

**Comment by Fenoxo** [comment]
Fixt via 9579875c16eb8c1d53d4f12cdda2c21cf58a1376
