### ISSUE TITLE
Vanae milk for players works like a tease attack

### ISSUE THREAD

**Issue by weee123** [Fenoxo/sourceTiTS#373]
hi according to the in game description of Vanae milk it should be acting like a lust attack because it is described as having an arousing effect that is based off of breast size so it should do a relatively fixed amount of lust damage based off of the players breast size even if the enemy is not vulnerable to teasing.

**Comment by Fenoxo** [comment]
Some concessions were made for balance and ease of code. It's treated as a super-powered chest tease basically. It hits more effectively than normal and does more damage.
