### ISSUE TITLE
Gianna Breast Appearance

### ISSUE THREAD

**Issue by blkdrgn** [Fenoxo/sourceTiTS#374]
Gianna's appearance says she has M-cup breasts, yet her silicone distribution says she isn't there yet. When increasing, it goes from E --> M in the appearance.
![tbb](https://cloud.githubusercontent.com/assets/12444405/7631535/6be59824-fa11-11e4-946b-70df12478f5e.PNG)
![tbb2](https://cloud.githubusercontent.com/assets/12444405/7631544/961249bc-fa11-11e4-9bbf-3a460caf321a.PNG)

**Comment by Fenoxo** [comment]
Should be fixed via ec67b175faefde4ba2dc8108c90d6f5ed65cbd05

Looks like there was a slight discrepancy in if checks.
