### ISSUE TITLE
mhenga.penny.as has a typo on line 2735

### ISSUE THREAD

**Issue by weee123** [Fenoxo/sourceTiTS#376]
Hi i was just trying to compile the code after i changed a few items and i found that in mhenga.penny.as on line 2735 you have:
else output("<i>Well we aren't done yet. I bet you can do it again!"</i>);

this gives an error to fix this i moved the " so the fixed version looks like this:
else output("<i>Well we aren't done yet. I bet you can do it again!</i>");

**Comment by Fenoxo** [comment]
Fixed via ca47a64015becbcacf219c63fc5b53890dafcc7d
