### ISSUE TITLE
Not Enough Allocated Storage Space to Save

### ISSUE THREAD

**Issue by superpheonixfire** [Fenoxo/sourceTiTS#378]
Not certain if this is an issue with TiTS or just the flash player, but the player works fine with everything else, including CoC. When a save is attempted, it reaches an error and asks for permission to allocate more memory to Flash. However, the prompt cannot be clicked on or navigated by keyboard. It locks the screen, so the program is stuck, but the player itself does not crash or freeze. The prompt simply does not have any interaction. Cannot click on the popup, cannot click off of it to make it disappear, no keyboard presses appear to work, though pressing enter causes the cursor to enter the 'processing' swirly circle, but that disappears as soon as the cursor is moved.
For reference, this is done by Swiff Player on Windows 7. As stated, this flash player works fine for other games, including CoC.
The TiTS version is 0.5.36, a public build.
It is Swiff Player 1.7.
Screenshot attached:
![notenoughstoragespace](https://cloud.githubusercontent.com/assets/12480125/7669236/e0f05bbe-fc2c-11e4-9692-e12808e63c16.png)

**Comment by superpheonixfire** [comment]
Right, the version is 0.5.36, a public build.

**Comment by Fenoxo** [comment]
That seems less like a problem with our game and more like a problem with the awful flash player you're using not letting you adjust flash's settings.

**Comment by superpheonixfire** [comment]
In the likely case this is an isolated case, is there a way to adjust Flash without a prompt? A config file or manager somewhere?
In an attempt to find a more concrete error, I tried also using Standalone Flash Player, which gave the same error without displaying a Flash prompt at all, and the Adobe Flash Player Projector. This last one gave an actual error report, as follows:

An ActionScript error has occurred.
Error #2044: Unhandled NetStatusEvent:. level=error, code=SharedObject.Flush.Failed

I have attached a screenshot of the player giving the error.
![shot2](https://cloud.githubusercontent.com/assets/12480125/7674283/28f54f2a-fce9-11e4-8c5e-f75439fe6391.png)

Interestingly, I found that the players do not have a problem with saving to a specific file. I don't know enough of how Flash is configured to request memory, it may only request additional memory if it attempts to save to AppData, but I found that to be an interesting quirk.

**Comment by Gedan** [comment]
Saving to a specific file doesn't use the monitored storage space that each individual Flash application can request; it only relates to "SharedObjects" stored as what is colloquially termed a Flash Cookie.

Finding actual solid documentation on all this shit is a literal nightmare, with a million and one conflicting tales of how all the pieces fit together. I'm going to fiddle with it a bit (mainly because I think I've just figured out how some piece of this whole puzzle was *intended* to work, if not immediately clear when first looking through the documentation).

**Comment by Gedan** [comment]
See bbb0fdf
