### ISSUE TITLE
Vanae Huntress Grapple

### ISSUE THREAD

**Issue by superpheonixfire** [Fenoxo/sourceTiTS#380]
When fighting a Vanae Huntress, if she manages to trip and grapple, the grapple seems to be inescapable. It will give the text that the struggle was successful, but then it immediately re-initiates the grapple. This continues until the battle results in a loss or the grapple is avoided, which has occurred once in four battles lost in this manner. Stats of the character in question are below. Not certain if this also occurs with Vanae Maidens, as I keep avoiding their trip attempts.
TiTS version 0.5.36.
Screenshot of example attached:
![vanaegrappleescape](https://cloud.githubusercontent.com/assets/12480125/7720087/c5d9c630-fe8e-11e4-92a3-0627da072545.png)

**Comment by Murphy540** [comment]
Vanae AI is to grapple if the PC is stunned, tripped, or grappled. This seems to be working as intended, you just seem to be rather unlucky.

**Comment by Fenoxo** [comment]
I wanna poke at this a little when I bugfix

**Comment by Fenoxo** [comment]
Guess geddy fixt what I wanted to look into already. Schwing!
