### ISSUE TITLE
Bugs in 0.5.39

### ISSUE THREAD

**Issue by EpicHamster** [Fenoxo/sourceTiTS#384]
Hello, ive been playing around ith the new version of tits and here are some of the bugs i found:
1)Text suddenly becomes bolded when in combat (all of it, if it helps, i have mimbranes assisting me, not sire if that is whats causing it)
2)Ovir ace always makes you get scales upon 1st use
3)Lizard tongue appears as just "tongue" in the character description even if its been transformed twoce and been made long.

**Comment by Fenoxo** [comment]
1) Bold bug has been fixed
2) Fixt
3) Fixed
