### ISSUE TITLE
Treatment breast growth completion message shows too early

### ISSUE THREAD

**Issue by AgRecluse** [Fenoxo/sourceTiTS#385]
And it looks like it'll play even after (if it doesn't play before) the big J -> JJ message as the code is right now.

**Comment by Fenoxo** [comment]
Couldn't seem to reproduce this one:

http://puu.sh/i5ySW/8f1833d398.png

Looks more or less fine to me (aside from the bold bug)

**Comment by AgRecluse** [comment]
I must have misread the messages. I''l double check before I post an issue next time.
