### ISSUE TITLE
Busts' bug [5.36]

### ISSUE THREAD

**Issue by Frahuenheld** [Fenoxo/sourceTiTS#387]
I deactivated the busts in the menu but I keep seeing the busts of Lyralla (clothed and naked), Nezhara (clothed and naked) and the Red Myr Guard.

**Comment by Fenoxo** [comment]
This one is a known issue with how I'm handling Jacques00 busts for the moment.

**Comment by Frahuenheld** [comment]
Oh right, he isn't in the busts' menu option.
