### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Frahuenheld** [Fenoxo/sourceTiTS#388]
tavros.reaha.as
On the Line 104 replace pc.mf("master","mistress") with the pc's name

**Comment by Fenoxo** [comment]
Fixt via dae76ae9f102a9e4dfe92435750e72b57d5f1543

**Comment by Fenoxo** [comment]
Fixt via dae76ae9f102a9e4dfe92435750e72b57d5f1543

**Comment by Fenoxo** [comment]
Huh... da248a528c2feddb13e646e9bd1fd6788b9e0257 doesn't seem to work

**Comment by Fenoxo** [comment]
Oh now it does. Fukkin' github.
