### ISSUE TITLE
Invite Saendra option doesnt work

### ISSUE THREAD

**Issue by MillaSteele** [Fenoxo/sourceTiTS#389]
when you hover over the option all it says is "Saendra isn't anywhere near this location. You'd have to catch Kiro on Tavros station to have Saendra in easy reach."

unless its not fully implemented that option is not usable atm

**Comment by Fenoxo** [comment]
Try meeting Kiro in the bar in Tavros Station.

**Comment by MillaSteele** [comment]
ok so my interet gave out before i could post again but i never knew she would show up o Mhen'ga but the scene works on Mhen'ga but not on Tavros its flipped

**Comment by eldestdawn** [comment]
When I'm on Tavros and the option is grey'd out saying "Saendra isn't anywhere near this location. You'd have to catch Kiro on Tavros Station to Saendra within easy reach." However when I'm on Mhen'ga, Myrellion or Tarkus, the option is available.

**Comment by Fenoxo** [comment]
Derp. It's been fixed.
