### ISSUE TITLE
one dimensional dick

### ISSUE THREAD

**Issue by muhname** [Fenoxo/sourceTiTS#391]
Where a penis would normally be located, you have instead grown your pair of huge, mutated cocks:Your pre-slicked prick is 3.5 inches long and 0 inches thick. It’s mottled pink and black in a very animalistic pattern. The ‘head’ of your shaft flares proudly, just like a horse’s. A small knot of thicker flesh is near the base of your animalistic cock, ready to expand to help you lodge it inside a female. The knot is 0 inches wide when at full size.

Second dick dont have this problem.

**Comment by Murphy540** [comment]
save pls

**Comment by muhname** [comment]
Nvm, mimbrane reset fixed it.
