### ISSUE TITLE
Hummus error

### ISSUE THREAD

**Issue by muhname** [Fenoxo/sourceTiTS#392]
You unwrap the bar and dig in, leaving a taste like hummus in your mouth. As the snack dissolves in your stomach, you feel the microsurgeons get to work.

Your face contorts, feeling slack like you’ve lost all control of your facial muscles. Thankfully this also seems to protect you from the pain of your skull reshaping, and doesn’t stop until you’ve got a human-like face.

You feel your skin tingle and notice the luminous silver swirls decorating your form starting to dissolve and fade. It doesn’t take long until your

Something bad happened!

Please report this message, and include any prior scene text or a description of what you did before seeing this message:

Version: 0.5.42

ReferenceError: Error #1069
	at classes.Items.Miscellaneous::TerranTreats/useFunction()
	at classes::TiTS/useItem()
	at classes::TiTS/buttonClick()

**Comment by Fenoxo** [comment]
Pretty sure I fixed this two days back via 7f17952b2131c7443081630dece96ab6be8f4b2a
