### ISSUE TITLE
null under bust corset

### ISSUE THREAD

**Issue by nekomundo** [Fenoxo/sourceTiTS#393]
I've noticed this several times across multiple character interactions, the underbust corset returns 'null' instead of its description. Here is a section of text from a (flat chested) male on male interaction with Vahn:

"With a cheeky smile, you decide to give him a little strip tease. Slowly and sensuously, you strip off your reinforced bodysuit before letting it fall to the floor. Reaching up, your null comes off – tossed aside and liberating your chest. Your zip pouch is slid off inch by inch, exposing your meaty, terran cock and apple-sized balls. Vahn lets out a very appreciative groan at the sight. His bushy blonde tail is wagging madly!"

Also I noticed that in this same scene Vahn is misspelled as Yahn.

"The air is filled with the lewd sound of your slapping thighs and your shared moans. You fuck him hot and hard against the crate, passionately pressing forward to meet his every backwards thrust. As you feverishly fuck his backside, Yahn groans and needily clenches your shaft, the half ausar quickly reaching his limit..."

**Comment by Fenoxo** [comment]
Not a problem with that item specifically - the problem there was the parser call was structured improperly. The same situation is likely appearing elsewhere - report 'em when you see 'em!

-Fixt
