### ISSUE TITLE
Kiro sex on Mhen'ga

### ISSUE THREAD

**Issue by nekomundo** [Fenoxo/sourceTiTS#394]
After winning the drinking contest with Kiro and choosing the option of riding her I found this error: 

Kiro burps and sighs, nodding, “Forgiveness !Unknown subject in “Master”!, but fuck-pet’s balls are going to swell up so big after this. It’s a Kui-tan quirk.”

**Comment by Gedan** [comment]
Think this has already been fixed. Checked the scene and didn't see any issues so.
