### ISSUE TITLE
Having wings that say you can fly do not make you fly

### ISSUE THREAD

**Issue by weee123** [Fenoxo/sourceTiTS#397]
if you save edit yourself to have wings that give you a description of being able to fly you do not get the flying version of the descent on the ant planet.

**Comment by Fenoxo** [comment]
Actually point out what wing type you're setting would go a long way to fixing this.

**Comment by weee123** [comment]
ok it is the large dragon wings i know that there is no legit way to get them yet but their description states that one flap of them is all that is needed to take to the air.

**Comment by Fenoxo** [comment]
Fixt via 35178e11a9bffed9c8c562c5c3ff9c25d8788bcc
