### ISSUE TITLE
[0.5.45] New Xenogen quest bug

### ISSUE THREAD

**Issue by Archee711** [Fenoxo/sourceTiTS#399]
During the scene where you get the blood vial from Lieve. It instead says that you've acquired an unfertilized venus pod. Strangely, you can turn the quest in while you possess it.
Only silly mode enabled, no save editing.

**Comment by Gedan** [comment]
Fixed - it's cause I copied the 'simplest' existing item we have to serve as a stub, and then forgot to update it after the fact to change all the descriptions. Under the hood it's still the correct item, it just had the wrong display names etc.
