### ISSUE TITLE
Typo/Misconception

### ISSUE THREAD

**Issue by Spectrumofchaos** [Fenoxo/sourceTiTS#403]
When you fly to Tarkus for the first time, this is part of the introduction:

For several minutes all you can hear is the hum of the shield generator much louder than before as it works to deflect and absorb much of the heat created <b>by drag</b> as you descend. 

It's a common misconception that drag is what causes objects to heat up when (re)entering an atmosphere. It's actually caused by atmospheric compression; the objects are moving so quickly that the air can't get out of the way fast enough. It's a minor issue, easiest way to fix it would be to simply omit "by drag" in that sentence.

**Comment by Fenoxo** [comment]
Fixt via bbe69a983b592c0e01b542a760dd31651b6d31f7
