### ISSUE TITLE
improper scene proc

### ISSUE THREAD

**Issue by Bjoob** [Fenoxo/sourceTiTS#405]
The scene where you find Anno and Kaede in Steele tech is capable of proccing directly after walking out of the back room, where you left Anno sleeping. This makes no sense in terms of continuity. Anywhos, this happened after having the riflery contest, winning, and choosing to nap with her. Directly after that event, the next thing that happened was the Anno/Kaede scene proc.

**Comment by Fenoxo** [comment]
Fixt via 14e42295b4d0a645a9272303e6e71f21bb0295cf
