### ISSUE TITLE
5.47 masturbation bug

### ISSUE THREAD

**Issue by Feralcus** [Fenoxo/sourceTiTS#406]
Character has cunt tail
When lust value is maxed out via "hand milk" hitting next gives a screen void of text. Hitting next again brings up the normal forced tail feeding scene.

Might be fixed in newer version I suppose but just in case.

**Comment by Fenoxo** [comment]
I glanced through the scene and couldn't spot a problem area. Could you upload a save file so that I can identify the source of the issue.

**Comment by Feralcus** [comment]
Errr, cool... How do I do that?

**Comment by Fenoxo** [comment]
It does, and thank you! Fixed via 5d6ced3e22d184f626f28867b16d4258d722fd3c
