### ISSUE TITLE
5.49 typo & a bug or two

### ISSUE THREAD

**Issue by Feralcus** [Fenoxo/sourceTiTS#408]
Dr Lash initial greeting
Missing a "to" here
I imagine it must be quite difficult for >>>you converse<<< with all those

Anno's shop on Tarkus. Kaede shows up and player indicates that they haven't met before but I had infact met her already when i got one of them distress signals and saved her from pirates, so yeah...

I was out on tarkus clicking through the various buttons on the bottom left and at some point the char stats button stayed highlighted with the purple outline even after i clicked it off.

Tarkus room descrip- unneeded "of" here.
you from seeing the whole way to down whatever is holding this >>>wreck of together.<<<

**Comment by Fenoxo** [comment]
Please put different issues in their own bug reports unless the appear to be related. I'm going to close this one and reopen for issues for the bugs I couldn't fix here.
