### ISSUE TITLE
[0.5.50] Weapon hack on Dr Lash

### ISSUE THREAD

**Issue by Archee711** [Fenoxo/sourceTiTS#409]
Not sure if this is just meant to prevent Techs from keeping his weapons disabled or if for some reason plasma pistols don't count as energy weapons, but when I use Weapon hack on Doctor Lash ability I get the following message:

"You try to hack Dr. Lash but there are no energy weapons to shut down!"

And the rest of the battle text for the turn.

**Comment by Fenoxo** [comment]
Fixt via 959cb0c9fec7aacb22b9177dab95a68ead711d6b
