### ISSUE TITLE
[0.5.42-0.5.50] No Zil...?

### ISSUE THREAD

**Issue by linksbro1** [Fenoxo/sourceTiTS#410]
Ever since the public 0.5.42 release, I haven't been unable to encounter ANY Zil, male or female, on Mhen'ga. I have only encountered Kerokoras in the northern forest, meaning I can't complete the capture Zil Quest. The problem hasn't been fixed in the 0.5.50 release.

**Comment by Fenoxo** [comment]
Turn off debug mode, yo.
