### ISSUE TITLE
5.50 typos

### ISSUE THREAD

**Issue by Feralcus** [Fenoxo/sourceTiTS#413]
Planet 4 "bathhouse" room descrip typo- 
 the view >>>with an as much<<< arousal as disdain.

   Bathhouse foyer descrip-
stands >>>behind the a simple<<< stone

Merchant queen lifestyle convo- Improper English here?  "bred"?
it’s not like they’re getting mistreated. >>>Just breed.<<<

Fungal depths room descrip-"an" > "and",
You don’t see a head >>>or even and end,<<< so it’s unclear

**Comment by Fenoxo** [comment]
Fixt 6781c68ec77280de257e31e841764eb6ac599d71
