### ISSUE TITLE
Button Highlight Sticking

### ISSUE THREAD

**Issue by Fenoxo** [Fenoxo/sourceTiTS#415]
"I was out on tarkus clicking through the various buttons on the bottom left and at some point the char stats button stayed highlighted with the purple outline even after i clicked it off."

**Comment by Gedan** [comment]
I changed a bunch of shit that probably cleared this up the other day. (In the past, all the buttons were setup to manually clear other buttons that could be active when their functionality was added, but nothing was retroactively changed when new menu functions got added...)
