### ISSUE TITLE
I don't know what happened

### ISSUE THREAD

**Issue by Dhonovan** [Fenoxo/sourceTiTS#416]
I attempted to load a save and an error message came up telling me to report it and past this message:

Version: 0.5.47

TypeError: Error #1009
	at classes::GUI/showModule()
	at classes::GUI/showTargetOutput()
	at classes::GUI/showPrimaryOutput()
	at classes.DataManager::DataManager/dataRouter()

Then I hit "next" and another message popped up telling me to send this in: 

Version: 0.5.47

TypeError: Error #1009
	at classes::TiTS/inCombat()
	at classes::TiTS/buttonClick()

Then any time I hit the "next" button after that, it displayed the same error message as above.

**Comment by Fenoxo** [comment]
Please attach your save so that we can look into it.

**Comment by Dhonovan** [comment]
Not a problem. Here you are.
 
Date: Tue, 21 Jul 2015 12:10:35 -0700

**Comment by Fenoxo** [comment]
I don't think github actually transmitted your email attachment. You'll have to host it somewhere (my forums should take saves as attachments) and link it here.

**Comment by Gedan** [comment]
No response close etc
