### ISSUE TITLE
Some Sylvanol TF's inactive it seems

### ISSUE THREAD

**Issue by flamefight** [Fenoxo/sourceTiTS#420]
I was mass using the latest transformative and noticed that the wiki's listings of transformations don't match up with the things it can actually do ((might just be wiki fault here but I thought I'd bring it up just in case))
- Both the 'Au Myrtille' and the 'Au Ronce' settings have changed player skin tone 0/100 times.
- Au Ronce was changing nipple/vagina/penis colors, but it only did it for the pale palette, possibly because the character's skin was already pale tone. ((Which the transformation made mention of the pale tone splotching out from))
- Au Ronce changed player's hair to transparent 0/100 times

I didn't test the elven settings yet, so i can't say if those are also faulty, and also this was done with the latest public build 0.5.50. So I am unaware if this issue has already been addressed in the latest patch.

**Comment by Fenoxo** [comment]
Transparent isn't a hair color and thus was cut. I just tried Au Ronce and it turned my skin gray on the first try.
