### ISSUE TITLE
Salon fur dying doesn't work for just arm fur

### ISSUE THREAD

**Issue by flamefight** [Fenoxo/sourceTiTS#421]
I tried dying my fur a color after I'd gotten rid of all my fur other than my Naleen cat arms & fur, having done a bit to lose and then regrow them as the patch notes said to do. However when I got to the option, fur dying was grayed out and unavailable. I re-checked to confirm I had the arm fur ((sure enough, fresh orange fur instead of my old cerulean stuff)), and then just bypassed the whole issue and grew a temporary tail to get the dying to work, which in the end solved the problem and got the arm fur dyed.

Just to make sure I wasn't crazy, I loaded up an old save and bought as many Terran Treats as I could and chugged them all. Ending up with the following body:

"You started your journey as a half-kaithrit, but you’ve become a naleen over the course of your adventures. You’re a good 6 feet and 1 inches tall by ancient imperial measurements and 1.85 meters in the more accepted metric system. Right now, you’re wearing a sexy transparent zipsuit, using plain panties for underwear, and girding your upper body with a furry bra.

Your face is human in shape and structure, with pale skin. Overall, your visage has a gorgeous profile with pouting lips, a button nose, and noticeable eyelashes. Like twinkling beacons, luminous blue eyes seem to draw the attention of everyone around you. Your long, luminous blue hair looks good on you, accentuating your features well. Your mouth contains a humanoid tongue.

You have a humanoid upper body with the usual torso, arms, hands, and fingers. Swirls of luminous blue trace brighter accents across much of your form. You have wide thighs that make you walk with a sexy, swinging gait, and your firm ass looks great under your gear. A sinuous, almost snake-like tail waves behind you, covered in skin like the rest of you except at the tip. There, it terminates in a clingy, wet, wiggly cunt that always seems to crave fresh sperm. Below your thighs, your flesh is fused together into a very long, snake-like tail, leaving a narrow, connecting gap between your crotch and butthole."

Clear of most of the transformations, I went and found as much Naleen Nip as I needed to get the arm fur back, and then shed all of the fur other than the arms. Ending up with this:

"Your face is human in shape and structure, with pale skin. Overall, your visage has a gorgeous profile with pouting lips, a button nose, and noticeable eyelashes. Metallically glistening gold eyes allow you to take in your surroundings without trouble. Your lengthy, luminous blue hair looks good on you, accentuating your features well. Your mouth contains a tongue.

You have a humanoid upper body with the usual torso, arms, hands, and fingers. Swirls of luminous blue trace brighter accents across much of your form. A coat of white fur covers your arms, giving them a distinctly animalistic bent. Your hands are still largely human in shape and dexterity aside from the fairly feline claws that have replaced your fingernails. You have flared thighs that make you walk with a sexy, swinging gait, and your petite posterior looks great under your gear. A sinuous, almost snake-like tail waves behind you, covered in skin like the rest of you except at the tip. There, it terminates in a venmon-pussy that always seems to crave fresh sperm. Below your thighs, your flesh is fused together into a very long, snake-like tail, leaving a narrow, connecting gap between your crotch and tailhole."

Then yet again, when I go back to the salon, the fur color option is grayed out and unavailable. This was done in the latest public build 0.5.50, so I am unaware if this issue was patched in the latest release.

**Comment by Fenoxo** [comment]
Seems like this was fixed a while back.
