### ISSUE TITLE
Three small typos/errors, one word corrections each

### ISSUE THREAD

**Issue by Grethos** [Fenoxo/sourceTiTS#426]
In the Myrellion Tavern Goo girl scene there is a clearOutput call where there should be a clearMenu call. (myrellion/tavern.as, line 428)

In the save editor UI there are two variables that got crossed. Currently it says tailGenitalArg = char.tailGenital and tailGenitalType = char.tailGenitalArg. It should be tailGenitalArg = char.tailGenitalArg and tailGenitalType = char.tailGenital. (UI/SEUserInterfaces.as, line 129)

In the Ellie scene, Ellie treats herms as females and will not let them penetrate her. Just changing one 'if' to an 'else if' will allow herms to penetrate her. (newTexas/Ellie.as, line 801)

**Comment by Gedan** [comment]
The Ellie stuff seems fine; Herms can end up going either way from that afaik so I don't understand what the problem is exactly.
