### ISSUE TITLE
Unable to encounter Deep Lake Queen as Male v. 0.5.53&54

### ISSUE THREAD

**Issue by stooduff** [Fenoxo/sourceTiTS#428]
I have not been able to encounter the deep lake queen as a male ( >= 1 penis, 0 vagina ). I'm unsure whether this is intended or an oversight or error on my part. The code seems to support only characters with vaginas ... see below

public function tryEncounterQueenOfTheDeep():Boolean
{
	if ((pc.hasVagina() && pc.fertility() > 0) && flags["QUEEN_OF_THE_DEEP_ENCOUNTERED"] == undefined && pc.findEmptyPregnancySlot(Creature.PREGSLOT_ANY) != -1)
	{
		queenOfTheDeepInitialEncounter();
		return true;
	}
	else
	{
		return DeepCavesBonus();
	}
}

Taken from  sourceTiTS/includes/myrellion/queenofthedeep.as

**Comment by Gedan** [comment]
Fixed it already. Something something commit hash.
