### ISSUE TITLE
Nova Goo Armor appearing at Myrellion bar after already owned.

### ISSUE THREAD

**Issue by stooduff** [Fenoxo/sourceTiTS#429]
Haven't looked to deep into the code of this one yet, but as geddy fixed another bug associated with this in last update he'll likely know how to fix quick. Explanation: I already own the goo armor but keep meeting it at the Myrellion bar for the recruit scene. Will add more detail if necessary.

**Comment by Gedan** [comment]
Fixed it already. Cba to find the commit hash.
