### ISSUE TITLE
TiTS_0.5.54 Problem with the Log's info

### ISSUE THREAD

**Issue by BobTheLost** [Fenoxo/sourceTiTS#430]
The log says I knocked out Tam but I choose the fuck her with dick option. The log also says that Lane has hypnotized me 5 times but really only done so twice. Sex with Sera is listed as undefined. Three-breasted waitress is listed as met but I didn't talk to her. Ceria is listed as if I touched her ears when I didn't, and the Sex bots in the Wastes are listed as encountered one of both genders but I encountered quite a few.

"* The Stellar Tether, Tarasque Crew: Knocked out Tam, Fucked Kaska, Dick-fucked Capt. Khorgan
Myrellion"
"* Sera, Times Sexed: undefined"
"* Ceria: Met her, Touched her ears"
"* Lane, Times Hypnotized: 5"
"* Female Sexbots, Times Encountered: 1
* Male Sexbots, Times Encountered: 1"

Sorry if these aren't a bug.

**Comment by Fenoxo** [comment]
Please attach your save file for verification purposes. If you need a place to host it, my forum will take them as attachments, then just crosslink it here.

**Comment by BobTheLost** [comment]
Sorry, but accessing to your site's forum causes my computer to freak out whenever I go there. I don't know why but going to your forums causes my monitor to flicker and my computer to auto shut down after 20 minutes after visiting your forums and only your forums causes this weird behavior. Is there another way to host the file?

PS: When I load the save in both 0.5.54 and 0.5.55 and compare the log I notice that the info is different form one version to the next. like 0.5.54 having "* The Stellar Tether, Tarasque Crew: Knocked out Tam, Fucked Kaska, Dick-fucked Capt. Khorgan Myrellion", but 0.5.55 has:
"* The Stellar Tether, Tarasque, Tam: Defeated her, Fucked her
* The Stellar Tether, Tarasque, Defenses: Destroyed rocket pods
* The Stellar Tether, Tarasque, Kaska: Defeated her, Fucked her
* The Stellar Tether, Tarasque, Capt. Khorgan: Defeated her, Dick-fucked her"
Some of the info that wasn't wrong before like:
"* Hand So: Listened to, Talked down to, kept the data bead" was changed wrongly to:
"* Hand So: Listened to, Talked down to, Disposed of data bead".
