### ISSUE TITLE
[0.5.55] Character Perks screen is bugged

### ISSUE THREAD

**Issue by BobTheLost** [Fenoxo/sourceTiTS#432]
Character Perks screen only shows this:

"Armor Piercing - Ranged attacks ignore the first few points of enemy defense.
Concentrate Fire - Allows consecutive ranged attacks to gain a bonus to damage.
Critical Blows - Your strikes and shots gain a 10% chance of inflicting double damage on normal melee and ranged attacks.
Detonation Charge - Grants the ability to throw a focused detonation charge at an enemy for very high Burning damage. Focusing the charge restricts the blast radius to a single target.
Heavy Weapons - Increases damage from Kinetic ranged weapons by 20%."

My character is level 8 yet only the first 5 levels are shown without the perks that are given to you automatically each level. Also the back button on the Character Perks screen doesn't work.

* please note that I am referring to the Character Perks screen that shows up when you press the Star button under the save/load button, Not the Perk selection screen.

**Comment by Fenoxo** [comment]
Fuxt
