### ISSUE TITLE
[Build 0.6.0] Queen Travia Peaceful path has no probe ending

### ISSUE THREAD

**Issue by primename** [Fenoxo/sourceTiTS#433]
“Your newly-minted mate is sitting on the edge of her throne’s dias, tending to the wounds her bodyguard suffered at at Dane’s hands. As you demanded, some of her warriors are dismantling her probe-throne, getting ready to dump it out into the village. Taivra looks at you with something between fear and admiration, and she keeps her hands well clear of her weapons.”

The probe is never taken to the surface and thus you never get the Shade encounter even though the text says that Queen Travia is removing the probe for you. Savin said that this was an oversight and that I should report it as a bug!

**Comment by Fenoxo** [comment]
I think the oversight is actually that the blurb about her warriors dismantling it appears, because in the peace path, you never actually make any demands about taking the probe, and your authority over her isn't really strong enough to order her to do that.

**Comment by primename** [comment]
So the option of talking to her about the probe is a lie?
