### ISSUE TITLE
Got no legs I suppose...

### ISSUE THREAD

**Issue by Feralcus** [Fenoxo/sourceTiTS#434]
Ver- 0.6.0
Loss against cuntsnake, new game with half ausar male, no tfs.

Two pin-pricks of pain hit your >>>>undefined leg<<<<, and you realize the creature is biting you again.

Loss against female zil-
 If you were standing right now, your undefined legs would be giving out from underneath you. 

Cunt snake masturbate scene-
It suctions harder and harder, pumping your prick up with fresh blood. Your undefined legs are twitching wildly from the pleasure,

**Comment by Fenoxo** [comment]
Fixt
