### ISSUE TITLE
New Saendra quest not available due to the message bleed 0.6.0/0.6.1

### ISSUE THREAD

**Issue by MinatoSteele** [Fenoxo/sourceTiTS#436]
Since I failed at the Sandra quest on my first try, I was thrown back a safe, to which the Saendra message bled over, without actually giving me permission to do the quest, which has me now unavailable to try the quest again and I cant even fail the quest, because it is as if the quest was never unlocked at all. 
My other saves were too old, so the only thing I did since then was the Taivra dungeon.

If you need the save, I have included it here
 https://www.dropbox.com/s/t04mh72875tjaau/Minato%20-%20185%20days.tits?dl=0
Thank you for all your good work

**Comment by Fenoxo** [comment]
Did the message bleedover happen in 0.6.0 or 0.6.1? It should be fixed in the latter.

**Comment by MinatoSteele** [comment]
Ah yeah sorry should have clarified that:
Bleedover happened in 0.6.0 and the bug I am having now is the "aftermath"

**Comment by Fenoxo** [comment]
Well the actual bug is fixed (the message bleed). What you're dealing with at this point is basically saves that have been corrupted by said bug.

I wouldn't hold your breath for anything official to clean them up.

**Comment by MinatoSteele** [comment]
ah ok thanks for listening though
I have found another thing, but thats also the same problem: If you have a save with the bleed through and then load an old FILE (example: I used a file from around 0.5.0) the bleedover is there after I register the space e-mail. 
To make it go away I need to load an old save and then the old file.
I dont know if it helps any people who have the problem, but thank you Fenoxo and crew for making awesome stuff
