### ISSUE TITLE
Email Report

### ISSUE THREAD

**Issue by Fenoxo** [Fenoxo/sourceTiTS#446]
Something bad happened!

Please report this message, and include any prior scene text or a description of what you did before seeing this message:

Version: 0.6.1

TypeError: Error #1010
	at classes::Creature/wettestVaginalWetness()
	at classes::TiTS/genesModsOverCounter()
	at classes::TiTS/buttonClick()

With Gene, on Myrellia.
Sex-->BellyRub-->Middle->OverTheCounter

**Comment by Gedan** [comment]
I think this is already fixed (potential access to a scene requiring a vagina missing the requisite check for presence was something I handled last week.)
