### ISSUE TITLE
Having tauric bodytype with non-equine legs still refers to body as equine.

### ISSUE THREAD

**Issue by Lycantiger** [Fenoxo/sourceTiTS#447]
includes/appearance.as (523-542)

		if(target.isTaur()) {
			//FATBUTT
			if(target.tone < 65) {
				output2(" Your " + target.buttDescript());
				if(target.buttRating() < 4) output2(" is lean, from what you can see of it.");
				if(target.buttRating() >= 4 && target.buttRating() < 6) output2(" looks fairly average.");
				if(target.buttRating() >= 6 && target.buttRating() <10) output2(" is fairly plump and healthy.");
				if(target.buttRating() >= 10 && target.buttRating() < 15) output2(" jiggles a bit as you trot around.");
				if(target.buttRating() >= 15 && target.buttRating() < 20) output2(" jiggles and wobbles as you trot about.");
				if(target.buttRating() >= 20) output2(" is obscenely large, bordering freakish, even for a horse.");
			}
			//GIRL LOOK AT DAT BOOTY
			else {
				output2(" Your " + target.buttDescript());
				if(target.buttRating() < 4) output2(" is barely noticable, showing off the muscles of your haunches.");
				if(target.buttRating() >= 4 && target.buttRating() < 6) output2(" matches your toned equine frame quite well.");
				if(target.buttRating() >= 6 && target.buttRating() <10) output2(" gives hints of just how much muscle you could put into a kick.");
				if(target.buttRating() >= 10 && target.buttRating() < 15) output2(" surges with muscle whenever you trot about.");
				if(target.buttRating() >= 15 && target.buttRating() < 20) output2(" flexes its considerable mass as you move.");
				if(target.buttRating() >= 20) output2(" is stacked with layers of muscle, huge even for a horse.");

**Comment by Fenoxo** [comment]
Fixt via 86e97353b0e9af428d2fe9df6dfbebaba1b8fc4a
