### ISSUE TITLE
Sex at Gene's Mods

### ISSUE THREAD

**Issue by jack9237** [Fenoxo/sourceTiTS#456]
the scene:
Do me over the counter,” you respond, holding his eye steadily. “Make it good.”

“I think,” says Gene, clacking his hard lips together and returning your stare, “I can maybe manage that.”

Gene lowers you down and flips you over with strong, careful sweeps of his claws, shifting himself forward as he does, the great shadow of his form looming over you, the cool, earthy smell of him in your nostrils. You shudder as you feel the swell of his chest touch you between the shoulder-blades; the sheer weight of him could easily keep you pinned here, naked with your firm rump in the air, if he so wished. You bite your lip as grey, warm digits caress and test the slick folds of your Error: Invalid vagina number (0) passed to vaginaDescript(); the hot, oak-like girth of his fanfir cock rides up between your buttocks, the ribs of its underside brushing over your null.

“Hmm,” he murmurs a moment later. “A pretty and charmingly sized lady-hole you have down here. Am I the type of brute to resize it as he pleases?” You inhale sharply as you feel the spear-head of his bigger dick restlessly press against your lips, stretching them wide. “No, of course not.” You exhale, a sigh of relief spiked with frustration as it withdraws. Gene arches his hips, bulky chest shifting down the small of your back, and the next moment you feel a more compact protrusion bump against your Error: Invalid vagina number (0) passed to vaginaDescript(). “Not when I deliberately come equipped for sweet pixies like you,” the fanfir growls. He thrusts forward, filling your tight tunnel with six inches of human cock.

The winged colossus’s hard thighs slap rhythmically against your firm butt as he pumps you, pressing deep into your wet depths, making you tingle with pleasure with each returning thrust. His huge, turgid bulge-cock slides between your thighs as he goes at you; you clench down, tightening your pussy up around his human cock at the same time as squeezing the soft flesh of your thighs around his bigger dick. Gene rumbles his enjoyment to this, and rewards you by picking up the pace, wing claws clutching the counter in order to provide the ballast to stretch the sensitive, clasping pocket you’ve provided with heavy, fervent strokes.

Gasps escape your mouth, hands clutching at the hard glass, your whole body shaking to the force of the massive beast mounting you, his hot, bullish dick pressing against a hidden spot which makes a steady stream of sparks run up your spine. Gasps become wanton moans as his robot hands clasp your chest and fondle your trembling nipples, stroking and pinching them until they are erect and inflamed. You arch your back as orgasm grasps you; you thrust back into Gene’s human dick gleefully, using its hard, full girth to clench up and squeal to the irrepressible joy of it, girl-cum

Something bad happened!

Please report this message, and include any prior scene text or a description of what you did before seeing this message:

Version: 0.6.1

TypeError: Error #1010
	at classes::Creature/wettestVaginalWetness()
	at classes::TiTS/genesModsOverCounter()
	at classes::TiTS/buttonClick()

**Comment by Fenoxo** [comment]
How the hell did you even get that scene? Looks like all the menus that lead to it gate it behind a check to see if you have a vagina.

**Comment by jack9237** [comment]
I was at the ant world the myr place and I talked to gene. I clicked the promps to rub his belly and selected middle. I then clicked on over the counter sex and this happened.

**Comment by Fenoxo** [comment]
I wonder if this is something I fixed already, and that's why I couldn't find anything wrong with it.

**Comment by jack9237** [comment]
I don't know I tried it with all of the other belly rubs with the exception of lower left I believe and they all did the same thing. The lower left, maybe, was the one where it was his "sensitive" spot and you could continue and get him off like that.

**Comment by Jacques00** [comment]
I just took a look at the history and this crash was fixed post-version 0.6.1 (it was probably fixed at around versions 0.6.2 or 0.6.3), so it may be possible to run into this issue if you are using that version. The original issue was that one of the buttons leading to genesModsOverCounter() was missing a vagina check.
