### ISSUE TITLE
Bess Robot

### ISSUE THREAD

**Issue by jack9237** [Fenoxo/sourceTiTS#459]
“Bess, can I please suckle your delicious breast milk?” You request of her, her eyebrows raising. She smiles and strides over to you, stroking her fingers down her swollen teats.

“... You want to suckle my nipples? It would be a shame if all that milk went to waste.” Brosive muses, happy to feed it to you. You take off your Atma Armor Mk. I, undershirt, and plain briefs, preferring to be naked for this.

Brosive quickly removes any obstructing clothing, tossing away her military outfit. Within moments, her massive motherly mammaries are proudly on display.

You openly ogle the milk dribbling from her puffy nipples. All of it is simply going to waste, but not for much longer. She climbs up into your lap - her full belly pressing against your chest - and holds one of her mammaries in one hand. She lifts it up for you to suckle upon.

“... How about a scrumptious milkshake, Lord Steele? My treat,” Brosive purrs seductively as you take her nipple between your lips. You can taste her cream squirting out onto your tongue. Her creamy fluid filling your mouth as you hungrily suck on her smothering mounds.

You can tell Brosive is thoroughly enjoying it as she lets out a rapturous moan, her head lolling back as you feed from her mounds. You cup her smooth I-cups in your hands and give them a cow-like squeeze, feeling her milk eagerly jet into your mouth.

“T-this feels so goood...” Brosive dreamily moans. You continue to milk her udders until she creams herself, overwhelmed by the sensory overload of you feeding on and squeezing her silvery lactating tits. As she cums, Brosive presses her smothering breasts against your face, her fingers pulling your head hard against them.

Soon it’s time for the other breast and you milk and suck on her buds, delighting in the sordid moans every time she squirts another jet of cream

You continue until you’ve sucked her silvery spheres dry, down to A-cup. Her thighs are a mess yellow honey, occasionally twitching as she falls back on the ground. Her nipples really are sensitive!

Something bad happened!

Please report this message, and include any prior scene text or a description of what you did before seeing this message:

Version: 0.6.7

TypeError: Error #1009
	at classes::TiTS/bessBreastFeed()
	at classes::TiTS/buttonClick()

**Comment by smrtone** [comment]
Got this error again:

"You continue until you’ve sucked her silvery spheres dry, down to A-cup. Her thighs are a mess girl-cum, occasionally twitching as she falls back on the ground. Her nipples really are sensitive!

Something bad happened!

Please report this message, and include any prior scene text or a description of what you did before seeing this message:

Version: 0.6.7

null"

**Comment by smrtone** [comment]
Noticed another error with her just now too. When selecting hip size, all of the options go to the size lower instead of the selected size. So "slender" produces "boyish", "average" produces "slender", "ample" produces "average", etc.
