### ISSUE TITLE
Infinite Syri Sex [Not a bug]

### ISSUE THREAD

**Issue by smrtone** [Fenoxo/sourceTiTS#460]
Not a bug, but you can infinitely loop sex with Syri by continually blowing her and then saying "don't go" and blowing her again.

**Comment by ambjoorn94** [comment]
I don't see what you're trying to suggest...
Is there something you want to change about it?

**Comment by smrtone** [comment]
Well I mean, it doesn't make sense logistically to infinitely have sex. Would make more sense to limit it to once more after the first round.

**Comment by Fenoxo** [comment]
I'm not really gonna sweat this one. Not really worth changing, and some folks might like it.
