### ISSUE TITLE
Raskvel things

### ISSUE THREAD

**Issue by Gedan** [Fenoxo/sourceTiTS#463]
This was reported in the CoC repo:

>When a genderless character encounters the Male Raskvel group, the options are the same as otherwise, but if you accept a sex offer it uses the male text, and reports 'NO WANG DETECTED' in the cock descript slot.

**Comment by Jacques00** [comment]
I tried looking for instances of this, but the only two parsers that can possibly return "ERROR: NO WANGS DETECTED..." are "pc.cocks" (for cocksDescript), and "pc.cockNounSimple" (for cocksNounSimple), both of which already have cock checks.

If this report is old, then it might have already been fixed!

**Comment by eldestdawn** [comment]
You feel leisured and sensuous at the centre of attention, happy to allow your partners the initiative and bask in the impression of being treasured. You hump yourself up onto the lap of one, curling your hand around his neck whilst surrounding his thick, purple penis with your compact, muscular butt, smirking provocatively as you splay your thighs to the other two, displaying your bare crotch. They don’t need any further encouragement. One of them wraps his hand around your ERROR: NO WANGS DETECTED for cocksDescript() and unspools his long, purple tongue. With a few teasing licks he’s got it sternly erect, and he wastes no time in sinking it into his mouth, running the soft, thin rasp of his mouth muscle along its sensitive underside. The other clambers over his brethren – earning him a muffled grunt of irritation as he manages to knee him in the head in his impatience – and sits his dense weight down on your flat belly. You find yourself deeply appreciative of how long and flexible raskvel tongues are as this one’s flicks over your nipples, quickly making them wet.


This was in Game Version: 0.6.9. When you choose the pay with sex option. It's the 3rd paragraph in the scene.

**Comment by eldestdawn** [comment]
There are other errors in the scene but that's because it's for male characters and the character is genderless.

**Comment by Jacques00** [comment]
K, I found the consensual scenes and put a genital check in front of them. Hope this helps!
