### ISSUE TITLE
Probe scene missing after Partnership with Taivra

### ISSUE THREAD

**Issue by RedMagma** [Fenoxo/sourceTiTS#464]
so at the end of the Taivra quest i convinced her to marry my character  or entered into partnership with or whatever and when i headed back i never got the scene for returning the probe and i reloaded and went a different path with the quest and the scene pop upped but it doesn't work for the partnership

**Comment by Fenoxo** [comment]
If you read the text, you do not acquire the probe when you marry her, merely get the coordinates.
