### ISSUE TITLE
Scoped Pistol still described as PC-manufactured if bought from Geoff (plus grammar)

### ISSUE THREAD

**Issue by Zeikfried** [Fenoxo/sourceTiTS#471]
current item descript: "This compact laser pistol is equiped with a rather impressive scope and energy cell of your own manufacture. It is quite accurate but relatively low powered."

fixes:
-omit 'of your own manufacture'
-'low powered' should be hyphenated

**Comment by Jacques00** [comment]
Okay, I edited it to match. I think the "of your own manufacture" bit was because the gun was initially unique to the Tech Specialist class--but apparently that isn't the case with Geoff able to sell all the starter guns to any class.
