### ISSUE TITLE
Clunky buttons arrangement

### ISSUE THREAD

**Issue by Kitteh6660** [Fenoxo/sourceTiTS#475]
As of right now, the button layout is messy. As you can see, some NPCs infringe on where the up and down buttons would be! The first row should be entirely dedicated for NPCs and objects.

It wouldn't be very hard to rearrange the button as shown. But then again, you'd have to check every single room to make sure no overlaps happen.

![buttonsarrangementproposal](https://cloud.githubusercontent.com/assets/5838739/10897956/f2c955c4-8193-11e5-851b-367f4c37cc18.png)

**Comment by Jacques00** [comment]
Potential fix has been implemented. (See changes above--Also, feel free to change as necessary.)
