### ISSUE TITLE
Possible to lock yourself out of the planetary tether without disarming bomb after defeating Khorgan

### ISSUE THREAD

**Issue by Bjoob** [Fenoxo/sourceTiTS#482]
As stated, it is possible to leave the tether without disarming the bomb. This means if that a game over is now imminent and unavoidable. Problematic if the player leaves post fight and saves.

**Comment by Fenoxo** [comment]
Actually, it's possible to run back to the nova (or your ship if very lucky) before it goes off and survive.

**Comment by Bjoob** [comment]
True, thank you for pointing that out. It's still an unfortunate mistake if you don't wish to nuke the planet, however.

**Comment by Fenoxo** [comment]
Generally it's a bad idea to take a bomb's detonator
