### ISSUE TITLE
Minor Bess Typo and Problem with inaccessable Bess titles

### ISSUE THREAD

**Issue by Peri2G** [Fenoxo/sourceTiTS#485]
When Bess has the first cleaning scene where she's changing the bed sheets and you select the option "Say Nothing" One of the pronoun variables doesn't display properly in the next scene. It displays something like "BessHeShe"

Also, when your relationship with Bess begins to improve, you unlock additional titles that she will call you and you can call her. However, the titles that she will call you is already filling all 15 buttons, and there doesn't seem to be a way to access the new titles as they are unlocked. 

The same problem exists for Bess's titles as well, with the additional problem that one of the titles is listed as "1" rather than any proper title. I can't remember when it unlocks unfortunately, but it is listed after "Mommy" which is a default title, and before "Friend" and "Buddy" So I think it may be the "Best Friend" title that says it unlocks in the scene where she is reading the Lord of the Rings and you try to confess your love for Bess. 

Also, since I have your attention. Thanks for the many happy nights of gaming! CoC inspired me to study programming to be able to make similar text games of my own!

**Comment by Jacques00** [comment]
I've corrected the pronoun typo and the title issue.

The buttons should have left and right page buttons on the lower right side of the interface, at the very bottom, in case there are more buttons you need to page through. If they are not functioning for you, let me know, but I think they are supposed to appear once a button list has surpassed its limit of 15 buttons per page.

**Comment by Peri2G** [comment]
My bad on that one. I see the buttons now. Thanks!
