### ISSUE TITLE
Gold Matron tries to find a Vagina

### ISSUE THREAD

**Issue by Peri2G** [Fenoxo/sourceTiTS#488]
When asking the Gold Matron fora  private bath then requesting that she treasure hunt, you get the following outcome.
"It doesn’t take long before she zeroes in on your ERROR: vaginasDescript called with no vaginas.. She strokes your cock once, then brushes your tip with her palm. “Ah, so you are a male.”"

**Comment by Jacques00** [comment]
Not sure what version  you are playing, but I recall this issue having been fixed here:
https://github.com/Fenoxo/sourceTiTS/commit/985531033bfb01983dc070a65723886ed3d9b13e

I think it was pushed through in the latest build (v0.6.14).
