### ISSUE TITLE
No option to discard or replace an item for Venus Pod if the inventory is full.

### ISSUE THREAD

**Issue by jb28147** [Fenoxo/sourceTiTS#492]
"You acquire an unfertilized venus pitcher seed pod (x1). There is no room in your inventory for your new acquisition. Do you discard the item or replace a filled item slot?"

There is no option to either discard the item or replace one of the item in the inventory for it as the only option available at the bottom is "Next".

**Comment by Fenoxo** [comment]
Is this in the latest version of the game?

**Comment by jb28147** [comment]
@Fenoxo 

The issue is in the latest version of the game.

**Comment by Jacques00** [comment]
Fix in the pull request (#490).

The scene was overwriting the loot screen's menu generation, so I omitted the conflicting lines.
