### ISSUE TITLE
grammar issue with Delilah

### ISSUE THREAD

**Issue by stealthymcdonkeypunch** [Fenoxo/sourceTiTS#509]
![grammar error](https://cloud.githubusercontent.com/assets/16007041/11381816/252e7e60-92b3-11e5-90a5-16947a13b62e.png)

Currently says "though you think there's a little more to than tone that dread"
Should say "though you think there's a little more to that tone than dread"

Thank you for your time

**Comment by Jacques00** [comment]
Potential fix has been implemented. (See changes above.)

**Comment by Fenoxo** [comment]
Marking as closed.
