### ISSUE TITLE
Naleen leg(iirc, code defines it as 1 snake\naga leg) issue when using GaloMax

### ISSUE THREAD

**Issue by Otaku-chan** [Fenoxo/sourceTiTS#510]
![naleen2rahn](https://cloud.githubusercontent.com/assets/10644454/11440537/3f8c2724-94d1-11e5-8366-e224b99536e5.png)

While trying to become a Rahn(galotian?) while currently a Naleen caused this to come up.
This screen is the third screen, and therefor does not come up unless you've edited your save.
I do not know if you're aware of the flaw, but in case you didn't I wanted to inform you so you could fix it before releasing the third Zo’dee encounter.

Also, null skin. I had 'glowing orange fur' (should it be 'glowing, orange fur'?) with 'pink skin' underneath, being a naleen, before starting the first GaloMax dose.
Not sure where it's pulling 'null' from.

**Comment by Jacques00** [comment]
Potential fixes have been implemented. (See changes above.)
