### ISSUE TITLE
Zo'dee and PC transformations

### ISSUE THREAD

**Issue by Otaku-chan** [Fenoxo/sourceTiTS#511]
Even if you look like a naleen, in the naleen habitat, Zo'dee will still identify you as a galactic traveller… Not sure if this can, or should, be fixed. Just thought I'd mention it, as it seemed a little odd to me.

It most likely applies to all worlds and full-transformations of their native creatures.

**Comment by Fenoxo** [comment]
I'm sure the core-ward gear and the way the PC comports themselves would give it away. Having a little something pop up would be nice, but keeping up with every variety of rimward native wouldnt be worth the effort.
