### ISSUE TITLE
Can Not Play CoC or TiTS in Browser

### ISSUE THREAD

**Issue by JamesDarkholme** [Fenoxo/sourceTiTS#512]
For whatever reason I can not seem to get either game to open in browser regardless of what browser I am using. I have tried it in Chrome, Firefox, and Microsoft Edge and none of the links to play either game in browser seem to be working. Fall of Eden works, but CoC and TiTS does not.

**Comment by Fenoxo** [comment]
There was a hitch with the pop-up player on the blog. It's been rectified.
