### ISSUE TITLE
Growing goo testicles bug

### ISSUE THREAD

**Issue by MillaSteele** [Fenoxo/sourceTiTS#520]
seems like you cant create more testicles it just stops mid sentence 

"You grab hold of your slippery sack and give the semi-solid nuts inside a familiar squeeze. Why stop at three balls when you can have even more? You bid your reserves of organic matter to flow down into your scrotum, pumping it up with a dripping-wet orb, a syrupy-slick spunk-factory. You finish crafting the new testicle in a matter of seconds. It bulges

**Comment by Jacques00** [comment]
You can only create up to 6 total, from what I gather. However, the bug should be squashed with the pull request #519. It was an output display issue--though functionally, the balls should still be gained if I'm not mistaken.

**Comment by MillaSteele** [comment]
well only have three and i tested it by getting rid of my two of my three. seems like the bug is that you cant create more then 2 anything past 2 itll stop mid sentence and not do anything
