### ISSUE TITLE
Critical Bug - 0.6.20 - Level Up button in Save Menu

### ISSUE THREAD

**Issue by RealoFoxtrot** [Fenoxo/sourceTiTS#522]
I have been able to repeat this problem on both the swf and APK versons.

Directions to repeat:
Open version 0.6.20
Click on Data
Click on the Level up button
Click on the Level up button again

Description:
When entering the Save menu from the main menu, I noticed the Level up button was active. 
Upon pressing it, I discovered it glitched out the game pretty badly, to the point where i couldn't get back and had to reboot the programme. Even the button to return to the main Menu was glitched out

**Comment by Jacques00** [comment]
I've made adjustments with the commits in pull request #519. Not sure if they will completely fix the issue, however. I can revert the changes if necessary.
