### ISSUE TITLE
[Version 0.6.20] MinoCharge.as

### ISSUE THREAD

**Issue by foxboy666** [Fenoxo/sourceTiTS#523]
![minocharge](https://cloud.githubusercontent.com/assets/14882071/11609393/a6fcbebe-9b8e-11e5-8d27-5580b1afb353.JPG)
I'm not that confident with my coding skills, but that looks like it would make hips decrease in size instead of increase when rating is lower than 4.
EDIT: File is classes/Items/Transformatives/MinoCharge.as

**Comment by Jacques00** [comment]
The issue has been looked at here:
https://github.com/Jacques00/sourceTiTS/commit/2b1cf29d7e5e0c3375313a61c559db9d9a8754ea

**Comment by foxboy666** [comment]
Yeah, but both have a "target.hipRatingRaw -= 1;" in them, so unless you change that it seems like the issue won't go away.

**Comment by Jacques00** [comment]
Ah, you are correct--thanks for pointing that out!
