### ISSUE TITLE
Can't take samples for Anno on Deck13

### ISSUE THREAD

**Issue by PinkysBrain** [Fenoxo/sourceTiTS#528]
Hi,

After completing Anno's mission on Deck13 I should be able to return and take samples, but the option isn't offered to me. I'm not familiar with AS, but I think line 2514 in anno.as is wrong

		if (flags["DECK13_SAMPLES_TAKEN"] < 3) addButton(1, "Goo Sample", deck13GooSample);

If the flag is undefined the comparison will fail right?

**Comment by Jacques00** [comment]
Yes, undefined values will fail the check.

**Comment by Fenoxo** [comment]
Gonna tag this as fixed. Reopen if it's broken after the next patch.
