### ISSUE TITLE
I Blame Jacques00 and Nonesuch for This:

### ISSUE THREAD

**Issue by Fenoxo** [Fenoxo/sourceTiTS#530]
You have a narrow, well defined but unostentatious six pack, capped with three 0.2-inch throbbing nipples each. The average-sized areolae are pink.

My six-pack has nipples. Awesome.

**Comment by Gedan** [comment]
Something something puppysluts.

**Comment by Jacques00** [comment]
Edited for subject clarity!

I knew something was off with those ab lines, but I didn't realize it until now--thanks for pointing it out!
