### ISSUE TITLE
Extra Data in Single Combat View

### ISSUE THREAD

**Issue by Fenoxo** [Fenoxo/sourceTiTS#543]
This shot is from the intro with Celise in 0.6.24: http://puu.sh/mhKFE/1ecc702ee0.png
This shot is from the RC1 build: http://puu.sh/mhKGU/a1c3ef8cd5.png

I don't mind it being there, but if we're going to have it there, we should at least disable it for Celise's initial fight.

**Comment by Gedan** [comment]
Fixed in 54f4023
