### ISSUE TITLE
0.6.25 RC2 Combat Problems - Tease broken

### ISSUE THREAD

**Issue by RealoFoxtrot** [Fenoxo/sourceTiTS#544]
Leaving this here because others have documented it,  but haven't written a report.

When using Tease:

Tease -> Target Enemy ->

Screen shows "Which tease skill will you use" followed immediately by Enemy's counter reaction.
Only option is "Next"

**Comment by dragontamer8740** [comment]
Seconded, definitely a real bug.

**Comment by Gedan** [comment]
Fixed in 83df855
