### ISSUE TITLE
0.6.25 RC2 Combat Problems - Special: Paralyzing Shock [Critical]

### ISSUE THREAD

**Issue by RealoFoxtrot** [Fenoxo/sourceTiTS#545]
This could be part of a wider problem, as haven't tested past this.

Using the Tech Special move P. Shock brings the game to a screen with no buttons active except the Menu buttons. The only way to continue is to load a previous save or start a new game

**Comment by Gedan** [comment]
Already resolved somewhere along the line. Made tweaks in 630c047
