### ISSUE TITLE
0.6.25 RC2 Group Combat

### ISSUE THREAD

**Issue by Jacques00** [Fenoxo/sourceTiTS#546]
Here are a clutter of issues I found with group combat during Saendra's "Fools Rush In" mission. I have yet to test this with other group battles, but I assume the issues are consistent.

In the first image:
![v0 6 25_rc2_battlebugs_01](https://cloud.githubusercontent.com/assets/13983936/12094843/00251890-b2d9-11e5-8701-b3b6c232e077.png)
* An issue with the text spacing--printing one or two extra lines between the "... side-by-side with your companion" and the "Together, you're..." sentences.
* The collapsed bust/name area looks fine (though I think it's okay if it retains the location info for consistency), however, it seems to be persistent outside of combat--so after victory in combat, the player will be stuck with that collapsed area until running into a singular enemy, where that block will be reset back to how it originally is. I suggest a UI reset after exiting combat, if possible.
* Choosing to use the "Carpet Grenade" special attack will indeed hit the entire group of enemies, but it does not clear the screen before printing, nor allow enemy actions after the attack has been used, resulting in the special to be stacked in the same turn until they are defeated. Once defeated, the player cannot attack or tease them, but rather wait, fantasize, or enter-exit inventory to progress with the battle's conclusion.

After beating the gang and approaching Saendra (again, with the bust/name block stuck in collapsed mode), I continued the mission to proceed to the other battles.

In the second image:
![v0 6 25_rc2_battlebugs_02](https://cloud.githubusercontent.com/assets/13983936/12094845/0027e070-b2d9-11e5-8d13-be8e07aae993.png)
* The new line issue still persists between the intro line and the line after it.
* The bust/name block resets here as it should (which isn't really a bug), fixing the collapsed issue from before.
* After rushing in and beating the mercenary guard, the bust/name block displays "FIGHT: ZIL MALE" when that's not what I was fighting. The bust image was also of my buddy, Saendra--I don't know if this is a stand-in, but if not, it seems to be a bug.
* Fenoxo mentioned this, but just in case it wasn't covered already: During singular battles, the date/time/author block shows up--not sure if this intentional but it should probably be hidden during combat for consistency (and pop back up outside of combat).
* Very minor: Upon victory, the right side bar displays only Steele's stats and Saendra's is totally left out. Though this is not a big issue, I suggest it continue to show the party's stats and then reset outside of combat.
* In this battle, I used the gray goo armor and sent her out--she doesn't return after combat with this opponent post-battle...

After the fight with the mercenary, the engineer pops up, starting another battle.

In the third image:
![v0 6 25_rc2_battlebugs_03](https://cloud.githubusercontent.com/assets/13983936/12094846/0028758a-b2d9-11e5-825d-215330a306e9.png)
* The new line and date/time/author issues are still there (of course!).
* Again, since the goo was never recalled after the other battle, choosing to recall her during this battle produces a crash error!

And that is as far as I got analyzing the group battles. If anything else noticeable pops up, I'll try to post it here or in a new report.

Hope this helps!

**Comment by Gedan** [comment]
Most/all of this should have been handled in various places over the last few days sooo...
