### ISSUE TITLE
Android cannot load any game

### ISSUE THREAD

**Issue by coladict** [Fenoxo/sourceTiTS#553]
Whether file or regular save, the game just freezes when using the new backers build. All my saves are from version 0.6.23

**Comment by ishist** [comment]
Saves from 0.6.24 same.

**Comment by Gedan** [comment]
Possibly resolved. 50/50 chance of it either being weirdness with some of the API suddenly throwing exceptions that it didn't used to the last time I tested it, or having a janky compile of the SWF.

**Comment by coladict** [comment]
I can confirm that it loaded from file for me now. Only difference from your code is I built it as an AIR 16 target. Haven't tried the 13 one.
