### ISSUE TITLE
Fungal Queen Robot Fight [Patreon Report]

### ISSUE THREAD

**Issue by Fenoxo** [Fenoxo/sourceTiTS#554]
Someone on Patreon left the following (source https://www.patreon.com/posts/4124863?cid=1180647):

wont let me help the Fungal Queen against the robot You tell the queen that you accept her terms, and will help her to fight the coming machine. She looks grateful, turning to the gold myr.

“Thank you. You help us more than you may know,” she says before her entire body begins to dissolve. The amount of spores in the room seems to double, thickly clouding the air and surrounding you like a tornado wherever you move. A similar barrier surrounds the gold myr and her sister, who now lies on the ground with a normal looking belly. From behind you comes an immense explosion, and you turn to find its source.

Flames wreath the corridor that leads to the cavern, and the mushrooms change from soothing blue to a panicked red strobe. A titanic construct walks through the fire on eight spidery legs, stopping at the door to stare at you. Its mechanical parts are covered in flashy plastic-looking tiles, but you can see a denser metal plating beneath them. A company label you don’t recognize is openly emblazoned on its shoulder, consisting of a number of erratic lightning bolts spreading from a thumbs up. A large flamethrower replaces a hand on one of its arms, while the other has a menacing diamond tipped pneumatic hammer. It notices you standing and releases what you assume is a prerecorded message.

“Innocent civilian. Move away from this area with haste. This Deconstruction Unit has been designated to purge all life in this section of the caves. If you stay, ERROR will hold no responsibility for your injuries,” it drones in a jovial voice. Afterwards it pauses, giving you time to leave. It’s too late for that now, so you ready your weapons and prepare to defend the queen’s ritual. The next time it talks it does so without the jovial warning tone.

“Brandishing weaponry against construction robots is a violation of U.G.C. property damage law, and this unit is authorized to engage in lethal self-defense. Engage and die,” it says, readying its tools to destroy you and your surroundings. The pilot flame of its arm bursts to life as a menacing addition to its statement. Suddenly a second voice joins in, apparently through a comm link attached to the machine.

“Sabine! Are you there?! Don’t worry, this thing’s gonna get you out of there. Your sister has some connections with these space-farers, though I never guessed it would be this easy to get something this big. They all think with their loins,” comes a womanly voice from atop the robot. You guess it must be a relation of one of the two myr girls, but luckily it doesn’t seem she’s come in person. You have no reason to hold back.You’re fighting the Deconstruction Unit.
The giant construct shoots small gouts of flame at surrounding mushrooms whenever its focus is not taken by you. Its pneumatic hammer pulverizes the crystal structures, shattering them like glass depending on where it hits when near them. Getting close to it might be dangerous. You have a limited amount of time before it destroys everything in the room, and a limited amount of defensible space to use before it destroys the spores that protect you.

Something bad happened!

Please report this message, and include any prior scene text or a description of what you did before seeing this message:

Version: 0.6.25

TypeError: Error #1009
	at classes::TiTS/updateGardeBotCover()
	at classes.GameData::CombatContainer/showCombatMenu()
	at classes.GameData::CombatContainer/beginCombat()
	at classes.GameData::CombatManager$/beginCombat()
	at classes::TiTS/buttonClick()

**Comment by Jacques00** [comment]
I think Gedan had this covered:
https://github.com/Fenoxo/sourceTiTS/commit/8c8ee6da270d7b1057c1cddb07991a49dc78affc

**Comment by Fenoxo** [comment]
Good call.
