### ISSUE TITLE
I can't avoid being roasted.

### ISSUE THREAD

**Issue by argenten** [Fenoxo/sourceTiTS#556]
You’re fighting the Deconstruction Unit.
The giant construct shoots small gouts of flame at surrounding mushrooms whenever its focus is not taken by you. Its pneumatic hammer pulverizes the crystal structures, shattering them like glass depending on where it hits when near them. Getting close to it might be dangerous. You have a limited amount of time before it destroys everything in the room, and a limited amount of defensible space to use before it destroys the spores that protect you.

Something bad happened!

Please report this message, and include any prior scene text or a description of what you did before seeing this message:

Version: 0.6.26

TypeError: Error #1009
	at classes::TiTS/gardeBotMove()
	at classes::TiTS/buttonClick()

**Comment by Jacques00** [comment]
Insert some edits that might fix the issue.
